<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2016
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
 /**
  * Fields
  */
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options']['protection']['label'] = array('Protection mode','Choose the protection mode');
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options']['protection']['user'] = 'User level (user)';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options']['protection']['user_group'] = 'User groups level (user_group)';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options']['protection']['member'] = 'Member level (member)';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options']['protection']['member_group'] = 'Member groups level (member_group)';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['isDownload']['protection']['label'] = array('Submit active user-/member','Auto submit current user (backend) or member (frontend) data when field has been submitted empty (empty option) or record is empty');
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['isDownload']['protection']['label_group'] = array('Submit active usergroup-/membergroup','Auto submit current usergroup (backend) or membergroup (frontend) data when field has been submitted empty (empty option) or record is empty');
