<?php

namespace ContainerQ5MxqW9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VH1AYW0_Contao_Fragment_Contao_FrontendModule_TwoFactorService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VH1AYW0.contao.fragment._contao.frontend_module.two_factor' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return ($container->privates['.service_locator.VH1AYW0'] ?? $container->load('get_ServiceLocator_VH1AYW0Service'))->withContext('contao.fragment._contao.frontend_module.two_factor', $container);
    }
}
