<?php

namespace ContainerQ5MxqW9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Debug_Security_Voter_ContaoNews_Security_NewsContentVoterService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the private '.debug.security.voter.contao_news.security.news_content_voter' shared service.
     *
     * @return \Symfony\Component\Security\Core\Authorization\Voter\TraceableVoter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/Authorization/Voter/TraceableVoter.php';

        $a = ($container->privates['contao_news.security.news_content_voter'] ?? $container->load('getContaoNews_Security_NewsContentVoterService'));

        if (isset($container->privates['.debug.security.voter.contao_news.security.news_content_voter'])) {
            return $container->privates['.debug.security.voter.contao_news.security.news_content_voter'];
        }
        $b = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['.debug.security.voter.contao_news.security.news_content_voter'])) {
            return $container->privates['.debug.security.voter.contao_news.security.news_content_voter'];
        }

        return $container->privates['.debug.security.voter.contao_news.security.news_content_voter'] = new \Symfony\Component\Security\Core\Authorization\Voter\TraceableVoter($a, $b);
    }
}
