<?php

namespace ContainerQ5MxqW9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCspReporterControllerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Contao\CoreBundle\Controller\CspReporterController' shared service.
     *
     * @return \Contao\CoreBundle\Controller\CspReporterController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Controller/CspReporterController.php';

        return $container->services['Contao\\CoreBundle\\Controller\\CspReporterController'] = new \Contao\CoreBundle\Controller\CspReporterController(($container->services['contao.framework'] ?? self::getContao_FrameworkService($container)), ($container->services['nelmio_security.csp_reporter_controller'] ?? $container->load('getNelmioSecurity_CspReporterControllerService')));
    }
}
