<?php

namespace ContainerQ5MxqW9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContao_Command_CronListService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the private 'contao.command.cron_list' shared service.
     *
     * @return \Contao\CoreBundle\Command\CronListCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Command/CronListCommand.php';

        $container->privates['contao.command.cron_list'] = $instance = new \Contao\CoreBundle\Command\CronListCommand(($container->services['contao.cron'] ?? $container->load('getContao_CronService')));

        $instance->setName('contao:cron:list');
        $instance->setDescription('Lists all available cron jobs and their intervals.');

        return $instance;
    }
}
