<?php

namespace ContainerQ5MxqW9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrineOrmHelperService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Codefog\HasteBundle\DoctrineOrmHelper' shared autowired service.
     *
     * @return \Codefog\HasteBundle\DoctrineOrmHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/codefog/contao-haste/src/DoctrineOrmHelper.php';

        $a = ($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container));

        if (isset($container->services['Codefog\\HasteBundle\\DoctrineOrmHelper'])) {
            return $container->services['Codefog\\HasteBundle\\DoctrineOrmHelper'];
        }
        $b = ($container->services['Codefog\\HasteBundle\\DcaRelationsManager'] ?? $container->load('getDcaRelationsManagerService'));

        if (isset($container->services['Codefog\\HasteBundle\\DoctrineOrmHelper'])) {
            return $container->services['Codefog\\HasteBundle\\DoctrineOrmHelper'];
        }
        $c = ($container->services['router'] ?? self::getRouterService($container));

        if (isset($container->services['Codefog\\HasteBundle\\DoctrineOrmHelper'])) {
            return $container->services['Codefog\\HasteBundle\\DoctrineOrmHelper'];
        }

        return $container->services['Codefog\\HasteBundle\\DoctrineOrmHelper'] = new \Codefog\HasteBundle\DoctrineOrmHelper(($container->services['contao.framework'] ?? self::getContao_FrameworkService($container)), $a, $b, $c, ($container->services['security.token_storage'] ?? self::getSecurity_TokenStorageService($container)));
    }
}
