<?php

namespace ContainerQ5MxqW9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormManagerFactoryService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Terminal42\MultipageFormsBundle\FormManagerFactory' shared service.
     *
     * @return \Terminal42\MultipageFormsBundle\FormManagerFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-mp_forms/src/FormManagerFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/terminal42/contao-mp_forms/src/FormManagerFactory.php';

        return $container->services['Terminal42\\MultipageFormsBundle\\FormManagerFactory'] = new \Terminal42\MultipageFormsBundle\FormManagerFactory(($container->services['contao.framework'] ?? self::getContao_FrameworkService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['Codefog\\HasteBundle\\UrlParser'] ?? $container->load('getUrlParserService')));
    }
}
