<?php

namespace ContainerQ5MxqW9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKnpMenu_MenuProvider_LazyService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the private 'knp_menu.menu_provider.lazy' shared service.
     *
     * @return \Knp\Menu\Provider\LazyProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/knplabs/knp-menu/src/Knp/Menu/Provider/MenuProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/knplabs/knp-menu/src/Knp/Menu/Provider/LazyProvider.php';

        return $container->privates['knp_menu.menu_provider.lazy'] = new \Knp\Menu\Provider\LazyProvider(['be_menu' => [#[\Closure(name: 'contao.menu.backend_builder', class: 'Contao\\CoreBundle\\Menu\\BackendMenuBuilder')] fn () => ($container->services['contao.menu.backend_builder'] ?? $container->load('getContao_Menu_BackendBuilderService')), 'buildMainMenu'], 'be_header_menu' => [#[\Closure(name: 'contao.menu.backend_builder', class: 'Contao\\CoreBundle\\Menu\\BackendMenuBuilder')] fn () => ($container->services['contao.menu.backend_builder'] ?? $container->load('getContao_Menu_BackendBuilderService')), 'buildHeaderMenu']]);
    }
}
