<?php

namespace ContainerQ5MxqW9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRobotsTxtControllerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Contao\CoreBundle\Controller\RobotsTxtController' shared service.
     *
     * @return \Contao\CoreBundle\Controller\RobotsTxtController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Controller/RobotsTxtController.php';

        return $container->services['Contao\\CoreBundle\\Controller\\RobotsTxtController'] = new \Contao\CoreBundle\Controller\RobotsTxtController(($container->services['contao.routing.page_finder'] ?? self::getContao_Routing_PageFinderService($container)), ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container)));
    }
}
