<?php

namespace ContainerQ5MxqW9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Authentication_SwitchuserListener_ContaoBackendService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the private 'security.authentication.switchuser_listener.contao_backend' shared service.
     *
     * @return \Symfony\Component\Security\Http\Firewall\SwitchUserListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Firewall/SwitchUserListener.php';

        $a = ($container->privates['debug.security.access.decision_manager'] ?? self::getDebug_Security_Access_DecisionManagerService($container));

        if (isset($container->privates['security.authentication.switchuser_listener.contao_backend'])) {
            return $container->privates['security.authentication.switchuser_listener.contao_backend'];
        }
        $b = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['security.authentication.switchuser_listener.contao_backend'])) {
            return $container->privates['security.authentication.switchuser_listener.contao_backend'];
        }
        $c = ($container->services['router'] ?? self::getRouterService($container));

        if (isset($container->privates['security.authentication.switchuser_listener.contao_backend'])) {
            return $container->privates['security.authentication.switchuser_listener.contao_backend'];
        }

        return $container->privates['security.authentication.switchuser_listener.contao_backend'] = new \Symfony\Component\Security\Http\Firewall\SwitchUserListener(($container->services['security.token_storage'] ?? self::getSecurity_TokenStorageService($container)), ($container->privates['contao.security.backend_user_provider'] ?? $container->load('getContao_Security_BackendUserProviderService')), ($container->privates['contao.security.user_checker'] ?? $container->load('getContao_Security_UserCheckerService')), 'contao_backend', $a, ($container->privates['monolog.logger.security'] ?? self::getMonolog_Logger_SecurityService($container)), '_switch_user', 'ROLE_ALLOWED_TO_SWITCH', $b, false, $c, NULL);
    }
}
