<?php

namespace ContainerQ5MxqW9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUndoManagerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelDevDebugContainer
{
    /**
     * Gets the public 'Codefog\HasteBundle\UndoManager' shared autowired service.
     *
     * @return \Codefog\HasteBundle\UndoManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/codefog/contao-haste/src/UndoManager.php';

        $a = ($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container));

        if (isset($container->services['Codefog\\HasteBundle\\UndoManager'])) {
            return $container->services['Codefog\\HasteBundle\\UndoManager'];
        }
        $b = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->services['Codefog\\HasteBundle\\UndoManager'])) {
            return $container->services['Codefog\\HasteBundle\\UndoManager'];
        }

        return $container->services['Codefog\\HasteBundle\\UndoManager'] = new \Codefog\HasteBundle\UndoManager($a, $b);
    }
}
