<?php
/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2013 
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['selectdb_table'][0] 		= 'Table';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['selectdb_table'][1] 		= 'Choose the source table';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['selectdb_key'][0]		= 'Key field';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['selectdb_key'][1]		= 'Please choose the field that should be the unique reference to the value. Default is ID';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['selectdb_value'][0]		= 'Value field';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['selectdb_value'][1]		= 'Please choose the field that contains the values';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['selectdb_sorting'][0]	= 'Sort field';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['selectdb_sorting'][1]	= 'Please choose the field that is the sorting reference.';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['selectdb_where'][0]		= 'Conditions';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['selectdb_where'][1]		= 'Here you can enter conditions that filter the result (e.g. published=1)';	