<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2016
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
/**
 * Errors
 */
$GLOBALS['TL_LANG']['XPT']['pct_themer']['no_active_pages_found'] 		= 'Keine aktiven Seiten gefunden';
$GLOBALS['TL_LANG']['XPT']['pct_themer']['no_export_data']			 	= 'Keine Export-Daten in der Session gefunden. Bitte führen Sie die Datensammlung erneut durch.';
$GLOBALS['TL_LANG']['XPT']['pct_themer']['import_already_done']			= 'Import wurde bereits ausgeführt. Leeren Sie Ihre Benutzer-Session für einen erneuten Import.';
$GLOBALS['TL_LANG']['XPT']['pct_themer']['no_theme_record_selected'] 	= 'Bitte wählen Sie einen Theme-Datensatz als Ziel für Modul-Datensätze.';
$GLOBALS['TL_LANG']['XPT']['pct_themer']['pages_with_no_layout_save'] 	= 'Seitenstränge ohne Theme-Designer Speicherpunkt vorhanden.';
