<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2016
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_page']['pct_theme'][0]			= 'Layout-Auswahl';
$GLOBALS['TL_LANG']['tl_page']['pct_theme'][1]			= 'Bitte wählen Sie das Layout aus.';
$GLOBALS['TL_LANG']['tl_page']['pct_theme_import'][0]	= 'Demo-Daten in diesen Seitenbaum importieren';
$GLOBALS['TL_LANG']['tl_page']['pct_theme_import'][1]	= 'Bei Speicherung werden die Demo-Daten in diesem Seitenbaum importiert';
$GLOBALS['TL_LANG']['tl_page']['pct_theme_cto'][0]		= 'Theme wählen';
$GLOBALS['TL_LANG']['tl_page']['pct_theme_cto'][1]		= 'Bitte wählen Sie den Theme-Datensatz, in den die demo-bezogenenen Modul-Datensätze hinzugefügt werden.';
$GLOBALS['TL_LANG']['tl_page']['pct_themedesigner_hidden'][0] = 'Theme-Designer verbergen';
$GLOBALS['TL_LANG']['tl_page']['pct_themedesigner_hidden'][1] = 'Den Theme-Designer für diesen Seitenstrang verbergen. Die Theme-Designer Anpassungen bleiben aktiv.';

/**
 * Legends
 */
$GLOBALS['TL_LANG']['tl_page']['pct_theme_legend']		= 'Theme-Designer-Einstellungen';

// References
if(count($GLOBALS['PCT_THEMER']['THEMES']) > 0)
{
	foreach($GLOBALS['PCT_THEMER']['THEMES'] as $key => $arr)
	{
		$GLOBALS['TL_LANG']['tl_page']['pct_theme'][$key] = $arr['label'] ?? $key;
	}
}

/**
 * Operations
 */
$GLOBALS['TL_LANG']['tl_page']['pct_theme_export'][0]	= 'Theme-Demo der Seite %s exportieren';
$GLOBALS['TL_LANG']['tl_page']['pct_theme_export'][1]	= 'Die Theme-Demodaten der Seite %s exportieren';
