<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2014
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['fuzzy'][0] 					= 'Ungenaue Suche';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['fuzzy'][1] 					= 'Findet "Contao" bei der Suche nach "con" (entspricht einer Suche mit Platzhaltern %LIKE%).';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['search_mode'][0] 			= 'Suchmodus';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['search_mode'][1] 			= 'Wählen Sie hier die Art des Suchmodus. Schlüsselwortsuche entspricht einer Suche mit Platzhaltern wie mysql LIKE. Freitextsuche entspricht einer Suche nach mysql FREETEXT und empfiehlt sich besonders für das Durchsuchen von langen Texten.';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['search_mode']['keyword'] 	= 'Schlüsselwortsuche (geeignet für einfache Textfelder)';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['search_mode']['freetext'] 	= 'Freitextsuche (geeignet für Textareas und lange Textpassagen)';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['autocomplete'][0] 			= 'Autom. Vervollständigung';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['autocomplete'][1] 			= 'Wörter und Suchergebnisse werden bereits bei der Eingabe gesucht und ausgegeben.';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['text']['module_id'][0] 		= 'CustomCatalog Liste Modul';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['text']['module_id'][1] 		= 'Wenn Sie neben den Wortvorschlägen bereits mögliche Ergebnisse anzeigen wollen, wählen Sie hier die zum Filter passende Liste. Das Filterset muss im Modul aktiv sein.';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['text']['customsql'][0] 		= 'Freie Feldauswahl';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['text']['customsql'][1] 		= 'Ergänzen Sie weitere Datenbank-Felder, die in die Suche einbezogen werden sollen. Unterstützt werden textbasierte bzw. frei lesbare Felder z.B. optionale Felder aus Geodaten-Attributen oder Bild-Attributen';