<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2014
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['timestamp_value'][0] 		= 'Fixed value';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['timestamp_value'][1] 		= 'Here you can set a fixed value for the filter, if value should no be fetched by an attribute.';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['timestamp_mode'][0] 		= 'Operation';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['timestamp_mode'][1] 		= 'Choose the filter operation';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['timestamp_mode']['ht'] 		= 'Higher [>]';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['timestamp_mode']['hte'] 	= 'Higher-euqal [>=]';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['timestamp_mode']['lt'] 		= 'Lower [<]';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['timestamp_mode']['lte'] 	= 'Lower-equal [<=]';
