<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2014
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['languageStrictMode'][0] = 'Strikter Modus';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['languageStrictMode'][1] = 'Der strikte Modus zeigt nur Einträge der gewählten Sprache an, ohne Fallback.';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['setLanguageText'][0] 	= 'Eigene Sprachenbezeichnungnen';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['setLanguageText'][1] 	= 'Wählen Sie hier, wenn Sie eigene Sprachenbezeichnungen festlegen wollen.';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['languageText'][0] 		= 'Sprachcode / Bezeichnung';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['languageText'][1] 		= 'Bitte geben Sie Ihre gewünschten Bezeichnungen pro Sprache ein. Beispiel: Wert:en | Bezeichnung: Englisch';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['defaultValue']['languageSwitch'][0] 	= 'Aktive Sprache';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['defaultValue']['languageSwitch'][1] 	= 'Wählen Sie eine Sprache aus. Der Filter wird NUR entsprechende Spracheinträge anzeigen ohne Fallback.';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['defaultValue']['languageSwitch']['__base__'] = 'Basis-Einträge';