<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2014
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['PCT_CUSTOMCATALOG']['XPT']['emptyDataContainerArray'] 			= 'The DataContainer array for table %s is empty. The script has been stopped. Please check your return values.'; 
$GLOBALS['TL_LANG']['PCT_CUSTOMCATALOG']['XPT']['customelements_version_too_low'] 	= 'Your current CustomCatalog version (%s) requires CustomElements version (%s). Current version is (%s). Please update CustomElements. CustomCatalog has been stopped from processing.'; 
$GLOBALS['TL_LANG']['PCT_CUSTOMCATALOG']['XPT']['reservedSqlWord']					= '"%s" is a reserved term. Please use a different term';