<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2014
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['tl_module']['customcatalog'][0]						= 'Name';
$GLOBALS['TL_LANG']['tl_module']['customcatalog'][1]						= 'Please choose a configuration.';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_jumpTo'][0]					= 'Redirect page';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_jumpTo'][1]					= 'Please choose the reader page the user will be redirected to.';
// template
$GLOBALS['TL_LANG']['tl_module']['customcatalog_template'][0]				= 'Template';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_template'][1]				= 'Please choose a template.';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_template_mod'][0]			= 'Module-Template';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_template_mod'][1]			= 'Please choose a template for the module.';
// list
$GLOBALS['TL_LANG']['tl_module']['customcatalog_limit'][0]					= 'Number of entries';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_limit'][1]					= 'Here you can set the number of entries.';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_offset'][0]					= 'Skip entries';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_offset'][1]					= 'Here you can set the number of items that should be skipped.';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_perPage'][0]				= 'Entries per page';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_perPage'][1]				= 'Here you can set the number of items per page. Enter 0 to disable the automatic page break.';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_sortField'][0]				= 'Order field';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_sortField'][1]				= 'Order the items by this field. (default: tstamp)';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_sorting'][0]				= 'Sorting';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_sorting'][1]				= 'Choose the sorting direction.';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_sorting']['asc']			= 'Ascending';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_sorting']['desc']			= 'Descending';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_sorting']['rand']			= 'Random';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_setVisibles']['att'][0] 	= 'Visible attributes';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_setVisibles']['att'][1] 	= 'Choose the fields/attributes visible. (no selection = all)';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_setVisibles']['fil'][0] 	= 'Visible filters';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_setVisibles']['fil'][1] 	= 'Choose the filters visible. (no selection = all)';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_visibles'][0]				= 'Visibles';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_visibles'][1]				= 'Choose the visible elements.';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_hideSitemap'][0]			= 'Hide in sitemap';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_hideSitemap'][1]			= 'Do not include this module in the sitemap';
// image setting
$GLOBALS['TL_LANG']['tl_module']['customcatalog_attr_image'][0]				= 'Bild-Attribute';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_attr_image'][1]				= 'Bitte wählen Sie ein oder mehrere Attribute aus. Leer für ALLE';
// filter
$GLOBALS['TL_LANG']['tl_module']['customcatalog_filtersets'][0]				= 'Filtersets';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_filtersets'][1]				= 'Please choose the filters set that have influence on the list view.';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_filter_submit'][0]			= 'Submit on change';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_filter_submit'][1]			= 'Reloads the page when changing a filter.';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_filter_method'][0]			= 'Method, URL-creation';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_filter_method'][1]			= 'The default method is GET (the filter values will be added to the url as GET parameters)';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_filter_method']['get']		= 'GET';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_filter_method']['post']		= 'POST';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_filter_formID'][0]			= 'Formular-ID';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_filter_formID'][1]			= 'Enter a formular-ID.';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_filter_showAll'][0]			= 'Show all on empty filter';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_filter_showAll'][1]			= 'If the filter returns an empty result the list will show all entries. Disable this option to get the opposite effect -> only hits will be displayed. (default is: show all)';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_filter_actLang'][0]			= 'Filter by active language';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_filter_actLang'][1]			= 'Select here to automatically select the entries of the active language.';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_filter_start'][0]			= '"Show from"-Filter';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_filter_start'][1]			= 'Choose a timestamp/date filter.';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_filter_stop'][0]			= '"Show until"-Filter';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_filter_stop'][1]			= 'Choose a timestamp/date filter.';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_filter_showAll_customcatalogfilter'][0]			= 'Show all values on empty results (only for filter conditions)';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_filter_showAll_customcatalogfilter'][1]			= 'In case of an empty result the value will be removed or stays available';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_sqlWhere'][0]				= 'Custom SQL condiction';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_sqlWhere'][1]				= 'Enter a custom sql condition. The condition will be added to the active filter. Example: (id=10) ';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_sqlSorting'][0]				= 'Custom SQL order';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_sqlSorting'][1]				= 'Enter your custom sql order condition. ORDER BY will be added automatically. Example: id DESC';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_filter_customIdList'][0]	= 'Custom selection';
$GLOBALS['TL_LANG']['tl_module']['customcatalog_filter_customIdList'][1]	= 'Choose the entries. The selection can be sorted.';


/**
 * Legends
 */
$GLOBALS['TL_LANG']['tl_module']['list_legend']								= 'List settings';
$GLOBALS['TL_LANG']['tl_module']['ffw_legend']								= 'Redirect settings';
$GLOBALS['TL_LANG']['tl_module']['filter_legend']							= 'Filter settings';
$GLOBALS['TL_LANG']['tl_module']['advanced_sql_legend']						= 'Custom SQL settings';