<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2014
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['tl_pct_customelement_group']['selector'][0]					= 'Group set';
$GLOBALS['TL_LANG']['tl_pct_customelement_group']['selector'][1]					= 'Choose the group set for this group.';

/**
 * Panels
 */
$GLOBALS['TL_LANG']['tl_pct_customelement_group']['panel']['groupset'] = array('Palette collection','');
$GLOBALS['TL_LANG']['tl_pct_customelement_group']['panel']['groupset']['new'] = '-- New collection from current list --';
$GLOBALS['TL_LANG']['tl_pct_customelement_group']['panel']['groupset']['edit'] = '-- Edit collections --';
$GLOBALS['TL_LANG']['tl_pct_customelement_group']['panel']['groupset']['default'] = 'Default';
$GLOBALS['TL_LANG']['tl_pct_customelement_group']['panel']['groupset']['label'] = '(%s attr. in %s groups)';

/**
 * Buttons
 */
$GLOBALS['TL_LANG']['tl_pct_customelement_group']['groupset']			= array('New group set','Create a new group set for the current groups.');