<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2016
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['addTitle'][0]				= 'Tile and description';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['addTitle'][1]				= 'By default the target column is shown as title.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['title'][0]					= 'Title';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['title'][1]					= 'Enter a job title.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['description'][0]			= 'Description';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['description'][1]			= 'Enter a job description';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['type'][0]					= 'Job type';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['type'][1]					= 'Choose the job type.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['type']['default']			= 'Default';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['type']['table']			= 'Table action';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['type']['field']			= 'Field action';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['source'][0]				= 'Source';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['source'][1]				= 'Choose the source.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['target'][0]				= 'Target';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['target'][1]				= 'Choose the target.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['action'][0]				= 'Action';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['action'][1]				= 'Choose the action to be executed. No selection = empty value (import) or keep current value (export)';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['action']['default']		= 'Default';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['action']['value']			= 'Fixed value';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['action']['sql']			= 'Custom SQL execution';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['action']['hook']			= 'Hook callback execution';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['action']['timestamp']		= 'Set date value';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['action']['source']			= 'Value from data source';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['action']['exclude']		= 'Ignore/exclude';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['action']['headline']		= 'Set Headline';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['action']['text']			= 'Text';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['action']['html']			= 'Code / HTML';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['action']['multiSRC']		= 'Multiple selctions';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['mode'][0]					= 'Mode';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['mode'][1]					= 'Choose the mode of the value import/export.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['mode']['copy']				= 'Value 1on1';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['mode']['hook']				= 'Konvert value via hook';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['mode']['uuidToBin']		= 'Unique-ID zo binary convertion';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['mode']['binToUuid']		= 'Binary to Unique-ID convertion';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['mode']['php']				= 'PHP function';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['valueSRC'][0]				= 'Fixed value';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['valueSRC'][1]				= 'Enter a fixed value or leave blank. Keeps auto_increment values alive (respect PRIMARY keys)';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['hookSRC'][0]				= 'Hook callback';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['hookSRC'][1]				= 'Choose a hook callback function. Hook array: $GLOBALS["PCT_CUSTOMCATALOG_API"]["HOOKS"]';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['sqlSRC'][0]				= 'Custom SQL';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['sqlSRC'][1]				= 'Enter your custom sql. The "?" placeholder will be replaced with the current source value. The return value can be capsuled in php method syntax e.g. (SELECT id FROM tl_article WHERE id=?)->id // Return value is: tl_article.id';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['tstampSRC'][0]				= 'Date value';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['tstampSRC'][1]				= 'Enter or choose a date value';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['published'][0]				= 'Active';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['published'][1]				= 'Job is active';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['onError'][0]				= 'On errors';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['onError'][1]				= 'Choose the action to be executed when errors occur. No selection: All errors will be recorded and the process will be continued (if possible).';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['onError']['skip']			= 'Skip job';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['onError']['escape']		= 'Abort job';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['code'][0]					= 'Custom code';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['code'][1]					= 'Enter your custom code. The "?" placehoder will be replaced with the current value.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['rule'][0]					= 'Rules';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['rule'][1]					= 'Execute this job only on certain conditions.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['rule']['import_rule']		= 'Import rules';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['rule']['update']			= 'Updates only';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['rule']['insert']			= 'Inserts only (new records ony)';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['rule']['export_rule']		= 'Export rules';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['reference'][0]				= 'Reference';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['reference'][1]				= 'Reasign the target field (remapping)';


// additional field descriptions
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['mode']['_hook_']			= 'Convert a value via hook function. Parameters are: myCallback($arrSource,$arrData,$objJob)';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['mode']['_php_']			= 'Convert a value via PHP function. Value placeholder = "?" or inserttag e.g.date("d.m.y",?),';


/**										  
 * Legends						  
 */										  
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['title_legend']				= 'General';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['settings_legend']			= 'Settings';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['expert_legend']			= 'Expert settings';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['action_legend']			= 'Valuation settings';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['error_legend']				= 'Error settings';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['exclude_legend']			= 'Exclude / rules settings';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['exclude_legend']			= 'Remapping settings';

/**										  
 * Buttons								  
 */										  
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['new'][0] 					= 'Add new job';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['new'][1] 					= 'Create a new API job';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['edit'][0] 					= 'Edit job';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['edit'][1] 					= 'Edit job %s';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['editheader'][0] 			= 'Edit API settings';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['editheader'][1] 			= 'Edit API settings';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['copy'][0] 					= 'Copy job';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['copy'][1] 					= 'Copy job %s';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['toggle'][0] 				= 'Toggle job';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['toggle'][1] 				= 'Toggle job %s';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['run'][0] 					= 'Execute job';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_job']['run'][1] 					= 'Execute job %s';