<?php
/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2013 
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options']['image'] = array('More options','Choose more options for this attribute');
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options']['image']['alt'] 		= 'Alternative text [alt]';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options']['image']['title'] 		= 'Title [title]';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options']['image']['size'] 		= 'Image size [size]';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options']['image']['imageUrl'] 	= 'Image link [imageUrl]';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options']['image']['fullsize'] 	= 'Lightbox/New window [fullsize]';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options']['image']['caption'] 	= 'Caption [caption]';

$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['image']['size']	 = array('Default image size','Set the defaultimage size'); 