<?php
/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2013 
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['aliasSource'] = array('Alias source','Choose the attribute to generate the alias from.');
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['number_format']['alias'] = array('Custom Alias','Enter a custom format to generate the alias. Use inserttags as placeholder for field values e.g. {{myField1}}_{{myField2}}. The regular alias source field be ignored.');