<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2014
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['tl_maintenance']['pct_customelements']['jobs'] 		= 'CustomElements Aufgaben';
$GLOBALS['TL_LANG']['tl_maintenance']['pct_customelements']['run_job'] 		= 'Starten';
$GLOBALS['TL_LANG']['tl_maintenance']['pct_customelements']['job_done']		= 'Aufgabe [%s] ausgeführt';

/**
 * Jobs
 */
$GLOBALS['TL_LANG']['tl_maintenance']['pct_customelements']['wizardupdater'][0] 			= 'Wizard Updaten';
$GLOBALS['TL_LANG']['tl_maintenance']['pct_customelements']['wizardupdater'][1] 			= 'Aktualisiert den Aufbau aller CustomElements Widget/Wizard-Daten und speichert diese nach dem aktuellen Version-Muster. (Ab Version 1.1.8 speichert jedes Widget in der aktuellen Struktur. Diese Funktion dient besonders dem Updaten älterer CustomElements Daten)';
$GLOBALS['TL_LANG']['tl_maintenance']['pct_customelements']['wizardUpdateComplete'] 		= 'Alle CustomElement Widgets/Wizards aktualisiert.';
$GLOBALS['TL_LANG']['tl_maintenance']['pct_customelements']['wizardUpdateLoading'] 			= 'CustomElement Widgets werden aktualisiert...';
$GLOBALS['TL_LANG']['tl_maintenance']['pct_customelements']['wizardupdater']['empty'] 		= 'Keine Widgets gefunden.';

$GLOBALS['TL_LANG']['tl_maintenance']['pct_customelements']['attributeupdater'][0] 			= 'Attribute konvertieren';
$GLOBALS['TL_LANG']['tl_maintenance']['pct_customelements']['attributeupdater'][1] 			= 'Aktualisiert die Datenspalten ausgewählter oder aller Attribute im Vault und schreibt diese entsprechend der Vorgabe um. Die Variable "saveDataAs" jedes Attributes steuert die Zielspalte im Vault. Standard ist [data] (varchar(255)). Sicherheitshinweis: Beim Umziehen von einer Datenquelle zu einer anderen können Datenverloren gehen z.b. von data_text zu data. Siehe MySQL Datenspalten und ihre Wertebereiche.';
$GLOBALS['TL_LANG']['tl_maintenance']['pct_customelements']['attributeUpdateComplete'] 		= 'Alle Attributes-Daten aktualisiert';
$GLOBALS['TL_LANG']['tl_maintenance']['pct_customelements']['attributeUpdateLoading'] 		= 'Attribut-Daten werden aktualisiert...';
$GLOBALS['TL_LANG']['tl_maintenance']['pct_customelements']['attributeupdater']['empty'] 	= 'Keine Attribut-Daten gefunden.';

$GLOBALS['TL_LANG']['tl_maintenance']['pct_customelements']['removeAttributeDataFromVault'][0] = 'Attribute-Daten aus Vault löschen';
$GLOBALS['TL_LANG']['tl_maintenance']['pct_customelements']['removeAttributeDataFromVault'][1] = 'Löscht alle Attribute-bezogenen Einträge aus tl_pct_customelement_vault, ausser die CE-Widget Datensätze. Dieser Vorgang ist nicht umkehrbar und dient dem Beräumen der Datenbank.';
$GLOBALS['TL_LANG']['tl_maintenance']['pct_customelements']['removeAttributeDataFromVault_effected'] = 'Datensätze gefunden: %s';
$GLOBALS['TL_LANG']['tl_maintenance']['pct_customelements']['removeAttributeDataFromVault_runLabel'] = 'Ausführen';
$GLOBALS['TL_LANG']['tl_maintenance']['pct_customelements']['resolveVault'][0] 			= 'Vault-Datenübertragung';
$GLOBALS['TL_LANG']['tl_maintenance']['pct_customelements']['resolveVault'][1] 			= 'Überträgt alle CustomElement-Daten aus dem Vault (tl_pct_customelement_vault) in die referenzierten Datensätze und löscht nach erfolgreicher Übertragung den Datensatz aus dem Vault. Datensätze deren Ziel-Datensätze nicht existieren (verwaiste Daten), werden aus dem Vault entfernt.';
$GLOBALS['TL_LANG']['tl_maintenance']['pct_customelements']['vaultUpdateLoading'] 		= 'Daten werden aktualisiert...';
$GLOBALS['TL_LANG']['tl_maintenance']['pct_customelements']['resolveVault']['empty'] 	= 'Keine Daten gefunden.';
$GLOBALS['TL_LANG']['tl_maintenance']['pct_customelements']['attributeUpdateComplete'] 	= 'Alle Daten aktualisiert';