<?php
/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2013 
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_pct_customelement']['title'][0]				= 'Titel';
$GLOBALS['TL_LANG']['tl_pct_customelement']['title'][1]				= 'Geben Sie dem Ihrem Inhaltselement einen Namen.';
$GLOBALS['TL_LANG']['tl_pct_customelement']['alias'][0]				= 'Alias';
$GLOBALS['TL_LANG']['tl_pct_customelement']['alias'][1]				= 'Geben Sie einen Alias für das Inhaltselement ein. Der Alias ist eine eindeutige Referenz zu diesem Element.';
$GLOBALS['TL_LANG']['tl_pct_customelement']['isCTE'][0]				= 'Als Inhaltselement bereitstellen';
$GLOBALS['TL_LANG']['tl_pct_customelement']['isCTE'][1]				= 'Wählen Sie, wenn Ihre Inhaltselement als ein Contao Inhaltselementen bereitgestellt werden soll.';
$GLOBALS['TL_LANG']['tl_pct_customelement']['isFMD'][0]				= 'Als Frontend-Modul bereitstellen';
$GLOBALS['TL_LANG']['tl_pct_customelement']['isFMD'][1]				= 'Wählen Sie, wenn Ihr Inhaltselement als ein Frontend-Modul bereitgestellt werden soll.';
$GLOBALS['TL_LANG']['tl_pct_customelement']['template'][0]			= 'Ausgabe-Template';
$GLOBALS['TL_LANG']['tl_pct_customelement']['template'][1]			= 'Wählen Sie ein individuelles Template für Ihr Inhaltselement aus.';
$GLOBALS['TL_LANG']['tl_pct_customelement']['protected'][0]			= 'Element schützen';
$GLOBALS['TL_LANG']['tl_pct_customelement']['protected'][1]			= 'Dieses Element nur bestimmten Benutzern oder Benutzergruppen im Backend anzeigen.';
$GLOBALS['TL_LANG']['tl_pct_customelement']['user_groups'][0]		= 'Erlaubte Benutzergruppen';
$GLOBALS['TL_LANG']['tl_pct_customelement']['user_groups'][1]		= 'Diese Gruppen können das Element sehen.';
$GLOBALS['TL_LANG']['tl_pct_customelement']['users'][0]				= 'Erlaubte Benutzer';
$GLOBALS['TL_LANG']['tl_pct_customelement']['users'][1]				= 'Diese Benutzer können das Element sehen.';
$GLOBALS['TL_LANG']['tl_pct_customelement']['isWrapper'][0]			= 'Ist Umschlag-Element';
$GLOBALS['TL_LANG']['tl_pct_customelement']['isWrapper'][1]			= 'Wählen Sie hier, wenn das Inhaltselement als Umschlag-/Wrapper-Element im Backend dargestellt werden soll. (Gilt nur für Inhaltselemente)';
$GLOBALS['TL_LANG']['tl_pct_customelement']['isWrapper']['start']	= 'Start-Element';
$GLOBALS['TL_LANG']['tl_pct_customelement']['isWrapper']['stop']	= 'Stop-Element';
$GLOBALS['TL_LANG']['tl_pct_customelement']['isWrapper']['divider']	= 'Trenner-Element';

/**
 * Legends
 */
$GLOBALS['TL_LANG']['tl_pct_customelement']['title_legend']			= 'Titel und Alias';
$GLOBALS['TL_LANG']['tl_pct_customelement']['expert_legend']		= 'Experten-Einstellungen';
$GLOBALS['TL_LANG']['tl_pct_customelement']['settings_legend']		= 'Einstellungen';
$GLOBALS['TL_LANG']['tl_pct_customelement']['template_legend']		= 'Template-Einstellungen';
$GLOBALS['TL_LANG']['tl_pct_customelement']['protected_legend']		= 'Zugriffsschutz';

/**
 * Buttons
 */
$GLOBALS['TL_LANG']['tl_pct_customelement']['new']        			= array('Neues Inhaltselement', 'Einen neues "Eigenes" Inhaltselement anlegen.');
$GLOBALS['TL_LANG']['tl_pct_customelement']['import']        		= array('Vorlagen importieren', 'Unsere Vorlagen importieren.');
$GLOBALS['TL_LANG']['tl_pct_customelement']['plugins']        		= array('Plugins verwalten', 'Aktivieren oder Deaktivieren Sie zusätzliche Plugins');
$GLOBALS['TL_LANG']['tl_pct_customelement']['edit'][0]				= 'Element bearbeiten';
$GLOBALS['TL_LANG']['tl_pct_customelement']['edit'][1]				= 'Element ID %s bearbeiten';
$GLOBALS['TL_LANG']['tl_pct_customelement']['copy'][0]				= 'Element kopieren';
$GLOBALS['TL_LANG']['tl_pct_customelement']['copy'][1]				= 'Element ID %s kopieren';
$GLOBALS['TL_LANG']['tl_pct_customelement']['delete'][0]			= 'Element entfernen';
$GLOBALS['TL_LANG']['tl_pct_customelement']['delete'][1]			= 'Element ID %s entfernen';
$GLOBALS['TL_LANG']['tl_pct_customelement']['show'][0]				= 'Details';
$GLOBALS['TL_LANG']['tl_pct_customelement']['show'][1]				= 'Details des Elements ID %s anzeigen';
$GLOBALS['TL_LANG']['tl_pct_customelement']['export'][0]			= 'Vorlage exportieren';
$GLOBALS['TL_LANG']['tl_pct_customelement']['export'][1]			= 'Vorlage exportieren ID %s';

/**
 * Labels
 */
$GLOBALS['TL_LANG']['tl_pct_customelement']['label']				= '%s <span class="info tl_gray">(Gruppen:%s Felder:%s)</span>';