<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2019
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['FMD']['pct_theme_settings'] 			= 'Theme-Features';
$GLOBALS['TL_LANG']['FMD']['pageimage'][0]					= 'Header';
$GLOBALS['TL_LANG']['FMD']['pagearticle'][0]				= 'Seiten-Artikel';
$GLOBALS['TL_LANG']['FMD']['portfoliolist'][0]				= 'Portfolio-Liste';
$GLOBALS['TL_LANG']['FMD']['portfoliofilter'][0]			= 'Portfolio-Filter';
$GLOBALS['TL_LANG']['FMD']['portfolioreader'][0]			= 'Portfolio-Leser';
$GLOBALS['TL_LANG']['CTE']['pct_contentelementsets_node'] = 'Block-Vorlagen';
$GLOBALS['TL_LANG']['CTE']['pct_contentelementsets'] = 'Block-Vorlagen';
$GLOBALS['TL_LANG']['CTE']['pct_contentelementset_start'][0] = 'Block-Vorlage [Start]';
$GLOBALS['TL_LANG']['CTE']['pct_contentelementset_start'][1] = 'Start :: %s';
$GLOBALS['TL_LANG']['CTE']['pct_contentelementset_stop'][0] = 'Block-Vorlage [Ende]';
$GLOBALS['TL_LANG']['CTE']['pct_contentelementset_stop'][1] = 'Ende :: %s';

// Keys
$GLOBALS['TL_LANG']['tl_content']['contentelementset'][0] = 'Block-Vorlagen Übersicht';
$GLOBALS['TL_LANG']['tl_content']['contentelementset'][1] = 'Einfügen nach Element '.\Contao\Input::get('pid');
$GLOBALS['TL_LANG']['tl_content']['contentelementset_export'][0] = 'Block-Vorlagen-Export';
$GLOBALS['TL_LANG']['tl_content']['contentelementset_export'][1] = 'Export';