<?php

namespace ContainerBhvFr3k;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContao_Listener_DataContainer_PersonalDataPasswordService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'contao.listener.data_container.personal_data_password' shared service.
     *
     * @return \Contao\CoreBundle\EventListener\DataContainer\PersonalDataPasswordListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/EventListener/DataContainer/PersonalDataPasswordListener.php';

        return $container->services['contao.listener.data_container.personal_data_password'] = new \Contao\CoreBundle\EventListener\DataContainer\PersonalDataPasswordListener(($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)), ($container->services['translator'] ?? self::getTranslatorService($container)), ($container->services['security.helper'] ?? self::getSecurity_HelperService($container)));
    }
}
