<?php

namespace ContainerBhvFr3k;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContao_Image_MetadataService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'contao.image.metadata' shared service.
     *
     * @return \Contao\Image\Metadata\MetadataReaderWriter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao/image/src/Metadata/MetadataReaderWriter.php';

        return $container->services['contao.image.metadata'] = new \Contao\Image\Metadata\MetadataReaderWriter(new RewindableGenerator(fn () => new \EmptyIterator(), 0), new RewindableGenerator(fn () => new \EmptyIterator(), 0));
    }
}
