<?php

namespace ContainerBhvFr3k;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContaoManager_Command_DotenvDumpService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the private 'contao_manager.command.dotenv_dump' shared service.
     *
     * @return \Symfony\Component\Dotenv\Command\DotenvDumpCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/dotenv/Command/DotenvDumpCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/manager-bundle/src/Dotenv/DotenvDumpCommandFactory.php';

        $container->privates['contao_manager.command.dotenv_dump'] = $instance = (new \Contao\ManagerBundle\Dotenv\DotenvDumpCommandFactory(\dirname(__DIR__, 4), 'prod'))->__invoke();

        $instance->setName('dotenv:dump');
        $instance->setDescription('Compile .env files to .env.local.php');

        return $instance;
    }
}
