<?php

namespace ContainerBhvFr3k;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHyperlinkControllerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Contao\CoreBundle\Controller\ContentElement\HyperlinkController' shared service.
     *
     * @return \Contao\CoreBundle\Controller\ContentElement\HyperlinkController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Fragment/FragmentOptionsAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Controller/AbstractFragmentController.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Controller/ContentElement/AbstractContentElementController.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Controller/ContentElement/HyperlinkController.php';

        $container->services['Contao\\CoreBundle\\Controller\\ContentElement\\HyperlinkController'] = $instance = new \Contao\CoreBundle\Controller\ContentElement\HyperlinkController(($container->services['contao.image.studio'] ?? $container->load('getContao_Image_StudioService')), ($container->services['contao.insert_tag.parser'] ?? $container->load('getContao_InsertTag_ParserService')));

        $instance->setContainer(($container->privates['.service_locator.gSfX.Ym'] ?? $container->load('get_ServiceLocator_GSfX_YmService'))->withContext('Contao\\CoreBundle\\Controller\\ContentElement\\HyperlinkController', $container));

        return $instance;
    }
}
