<?php

namespace ContainerBhvFr3k;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRedirectControllerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Contao\CoreBundle\Controller\RedirectController' shared service.
     *
     * @return \Contao\CoreBundle\Controller\RedirectController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Controller/RedirectController.php';

        return $container->services['Contao\\CoreBundle\\Controller\\RedirectController'] = new \Contao\CoreBundle\Controller\RedirectController(($container->services['Symfony\\Bundle\\FrameworkBundle\\Controller\\RedirectController'] ?? $container->load('getRedirectController2Service')));
    }
}
