<?php
/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2013 
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['defaultValue']['fixedColumn'] = array('Feldwert','Legen Sie den Feldwert fest. Inserttags sind erlaubt. Beispiel: Fixer Unix-Zeitstempel: {{date::U}}');
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options']['fixedColumn'] = array('Speicherzeitpunkt','Wählen Sie wann der Standardwert gespeichert werden soll.');
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options']['fixedColumn']['oncreate'] = 'Erstellung des Eintrags (Wert wird einmalig geschrieben) [oncreate]';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options']['fixedColumn']['onsubmit'] = 'Speicherung des Eintrags (Wert wird geupdated) [onsubmit]';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['eval_rowscols'] = array('SQL Feldtyp',"Legen Sie den Feldwert in der Datenbank fest. (Standard: varchar(255) NOT NULL default ''");