<?php 
/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2013 
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['tl_content']['revolutionslider'][0]						= 'Auswahl';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider'][1]						= 'Wählen Sie einen der verfügbaren Slider aus.';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_data_easing'][0]			= 'Effektdarstellung';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_data_easing'][1]			= 'Legen Sie die Effektdarstellung fest.';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_data_start'][0]				= 'Startverzögerung (in Sek.)';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_data_start'][1]				= 'Startzeit nachdem das Element in den Slide animiert wird.';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_data_speed'][0]				= 'Effektdauer (in Sek.)';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_data_speed'][1]				= 'Legen Sie die Geschwindigkeit des Effekts fest. (Eingabe in Sekunden)';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_data_delay'][0]				= 'Startverzögerung der Texteffekte / Buchstabeneffekte. ';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_data_delay'][1]				= 'Werte möglich zwischen 0 und 100. Je höher die Anzahl an Wörtern oder Zeichen, desto höher sollte dieser Wert sein.';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_data_position'][0]			= 'Position X / Y';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_data_position'][1]			= 'Legen Sie die x,y Position des Elements im Slider fest. Mögliche Werte x-Position: left, center, right (oder Pixel). y-Position, z-Position in Pixel zwischen -2500 und 2500.';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_data_position_offset'][0]	= 'Offset-Position X / Y';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_data_position_offset'][1]	= 'Legen Sie die Offset- x,y Position des Elements im Slider fest. Mögliche Werte x-Position: left, center, right (oder Pixel). y-Position, z-Position in Pixel zwischen -2500 und 2500.';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_data_position_m'][0]		= 'Position X / Y (mobil)';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_data_position_m'][1]		= 'Legen Sie die x,y Position des Elements im Slider fest. Mögliche Werte x-Position: left, center, right (oder Pixel). y-Position, z-Position in Pixel zwischen -2500 und 2500.';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_data_position_offset_m'][0]	= 'Offset-Position X / Y (mobil)';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_data_position_offset_m'][1]	= 'Legen Sie die Offset- x,y Position des Elements im Slider fest. Mögliche Werte x-Position: left, center, right (oder Pixel). y-Position, z-Position in Pixel zwischen -2500 und 2500.';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_data_rotation'][0]			= 'Rotation X / Y / Z';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_data_rotation'][1]			= 'Legen Sie die x,y,z Rotation des Elements im Slider fest. Werte sind in ° Grad';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_data_lineheight'][0]		= 'Line-height | Line-height (mobile)';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_data_lineheight'][1]		= 'Legen Sie die line-height für Desktop und mobile Darstellungen fest.';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_data_scale'][0]				= 'Skalierung X / Y';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_data_scale'][1]				= 'Legen Sie die x,y Skalierung des Elements im Slider fest. Werte sind in % Prozent';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_data_skew'][0]				= 'Biegung X / Y';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_data_skew'][1]				= 'Legen Sie die x,y Biegung/Versatz des Elements im Slider fest. Werte sind in ° Grad';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_data_opacity'][0]			= 'Transparenz';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_data_opacity'][1]			= 'Legen Sie die Transparenz des Elements im Slider fest. Werte sind in % Prozent';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_data_perspective'][0]		= 'Perspektive';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_data_perspective'][1]		= 'Legen Sie die perspektivische Verzerrung des Elements im Slider fest. Wertebereich 300-1600';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_data_origin'][0]			= 'Ausgangspunkt X / Y';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_data_origin'][1]			= 'Legen Sie den Ausgangspunkt der Berechnungen des Elements im Slider fest. Werte sind in % Prozent';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_data_animation_start'][0]	= 'Start-Animationsart';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_data_animation_start'][1]	= 'Wählen Sie die Start-Animationsart. Wählen Sie "Custom Incoming animation" um die Erweiterte Effekt-Palette für die eingehenden Animationen zu laden.';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_data_animation_end'][0]		= 'End-Animationsart';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_data_animation_end'][1]		= 'Wählen Sie die End-Animationsart. Wählen Sie "Custom Outgoing animation" um die Erweiterte Effekt-Palette für die ausgehenden Animationen zu laden.';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_data_autoplay'][0]			= 'Autoplay';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_data_autoplay'][1]			= 'Das Video automatisch starten.';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_data_split'][0]				= 'Texteffekt / Buchstabeneffekt';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_data_split'][1]				= 'Wählen Sie einen Texteffekt';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_data_nextslideatend'][0]	= 'Nächsten Slide anzeigen bei Video-Ende';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_data_nextslideatend'][1]	= 'Den nächsten Slide automatisch anzeigen wenn das Video beendet ist.';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_videoType'][0]				= 'Video Quelle wählen';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_videoType'][1]				= 'Wählen Sie die Quelle für das Video.';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_videoType']['local']		= 'MP4 Videodateien';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_videoType']['external']		= 'Externes Video (YouTube, Vimeo)';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_videoType']['youtube']		= 'YouTube';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_videoType']['vimeo']		= 'Vimeo';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_video_singleSRC'][0]		= 'Vorschaubild';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_video_singleSRC'][1]		= 'Wählen Sie das Vorschaubild für das Video.';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_video_controls'][0]			= 'Bedienelemente hinzufügen';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_video_controls'][1]			= 'Dem Video die Browser/HTML5 Bedienleiste hinzufügen (fügt dem <video> Element das Attribut controls hinzu)';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_video_loop'][0]				= 'Endlosschleife';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_video_loop'][1]				= 'Das Video in einer Schleife abspielen (fügt dem <video> Element das Attribut loop hinzu)';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_video_boxed'][0]			= 'Video nicht füllend';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_video_boxed'][1]			= 'Das Video nicht auf die Sliderbreite skalieren.';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_video_size'][0]				= 'Videogröße Breite/Höhe';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_video_size'][1]				= 'Geben Sie die Größe des Videos in Pixel oder Prozent an. Bsp.: 800 oder 100%';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_video_fullscreen'][0]		= 'Fullscreen Video';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_video_fullscreen'][1]		= 'Das Video als "Fullscreen" Video darstellen. Wenn Slider in Fullscreen mode wird das Video automatisch als Fullscreen Video dargestellt.';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_data_pos9grid'][0]			= 'Relative Position';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_data_pos9grid'][1]			= 'Legen Sie die relative Postion des Elements im Slider fest.';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_data_frames'][0]			= 'Frame by Frame custom animation';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_data_frames'][1]			= 'Ergänzen Sie Ihre eigenen Animations-Sequenzen für dieses Element.';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_OUT'][0]					= 'OUTgoing (ausfahrende) Animations Editor';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_OUT'][1]					= 'Wählen Sie hier, falls Sie die  Einstellungen für die ausgehende Animation getrennt steuern wollen.';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_text'][0]					= 'Text';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_text'][1]					= 'Bitte geben Sie den darzustellenden Text ein.';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_text_fontsize'][0]			= 'Textgröße, Skalierungs-Ausgangsgröße (px) / (mobile)';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_text_fontsize'][1]			= 'Bitte geben Sie die Schrift-Ausgangsgröße an. Der Wert (in Pixel) dient als Berechnungsgrundlage, ausgehend von der Desktop-Sliderbreite, für die Skalierung der Schriftgröße.';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_text_invertcolor'][0]		= 'Farben umdrehen';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_text_invertcolor'][1]		= 'Wählen Sie hier, wenn die Farben invertiert werden sollen.';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_text_bold'][0]				= 'Headline / Fett gedruckt';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_text_bold'][1]				= 'Wählen Sie hier für fett-gedruckten Text.';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_text_italic'][0]			= 'Kursiv';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_text_italic'][1]			= 'Den Text kursiv darstellen.';
$GLOBALS['TL_LANG']['tl_content']['useSVG'][0]									= 'SVG ausgeben';
$GLOBALS['TL_LANG']['tl_content']['useSVG'][1]									= 'Das gewählt Bild als SVG ausgeben. (Bild-Typ muss SVG sein)';
$GLOBALS['TL_LANG']['tl_content']['hideMobile'][0]								= 'Mobile ausblenden';
$GLOBALS['TL_LANG']['tl_content']['hideMobile'][1]								= 'Auf Mobilen Geräten ausblenden';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_visibility'][0]				= 'Sichtbarkeitssteuerung';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_visibility'][1]				= 'Legen Sie fest auf welchen Geräten das Element nicht angezeigt wird.';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_visibility_ref'][1]			= 'Mobil ausblenden';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_visibility_ref'][2]			= 'Desktop ausblenden';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_frames'][0]					= 'Eigene Animations-Definition festlegen';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_frames'][1]					= 'Eine eigene Animations-Definition festlegen, basierend auf dem data-frames Attribute. (überschreibt alle Effekt-Einstellungen).<p class="tl_help">Gehe zu: <a href="https://www.themepunch.com/revsliderjquery-doc/layer-transitions/" target="_blank">Dokumentation Themepunch</a></p>';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_data_frames'][0]			= 'Eigene data-frames Definition';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_data_frames'][1]			= 'Geben Sie die data-frames json Definitionen einen.';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_video_aspect'][0]			= 'Seitenverhältnis';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_video_aspect'][1]			= 'Hier können Sie das Seitenverhältnis des Videos auswählen, um es responsive zu machen.';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_parallax'][0]				= 'Parallax-Level';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider_parallax'][1]				= 'Wählen Sie ein Parallax-Level aus, um den Parallax-Effekt für dieses Element zu aktivieren.';

// overwrites
$GLOBALS['TL_LANG']['tl_content']['revolutionslider']['url'][0]					= 'Video URL';
$GLOBALS['TL_LANG']['tl_content']['revolutionslider']['url'][1]					= 'Geben Sie die URL zum Video an. YouTube Videos müssen über den "einbetten"-Link eingefügt werden z.b. http://www.youtube.com/embed/QeMbgvqtIqg.</br>Zusätzliche Parameter können über GET Parameter ergänzt werden. z.B. ?rel=0, wenn bei Youtube Video keine verwandten Videos am Ende angezeigt werden sollen. Siehe: https://developers.google.com/youtube/player_parameters?hl=de';


/**
 * Legends
 */
$GLOBALS['TL_LANG']['tl_content']['slide_legend']								= 'Zusätzliche Slider-Einstellungen';
$GLOBALS['TL_LANG']['tl_content']['select_legend']								= 'Auswahl';
$GLOBALS['TL_LANG']['tl_content']['video_settings_legend']						= 'Video-Einstellungen';
$GLOBALS['TL_LANG']['tl_content']['position_legend']							= 'Positions-Einstellungen';
$GLOBALS['TL_LANG']['tl_content']['effect_legend']								= 'Effekt-Einstellungen';
