<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2015
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['defaultValue']['geolocation'][0] 			= 'Zentrum der Umkreissuche (Breitengrad / Längengrad)';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['defaultValue']['geolocation'][1] 			= 'Geben Sie die Koordinaten des Zentrums der Suche ein.';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['defaultMulti']['geolocation'][0] 					= 'Google-Geocoder-API Schlüssel';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['defaultMulti']['geolocation'][1] 					= 'Geben Sie Ihren Google-Geocoder API Schlüssel ein. Leer lassen für die Verwendung des Openstreetmap Geocoders.';