<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2019
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
/**
 * Fields
 */
// newslist filter
$GLOBALS['TL_LANG']['tl_module']['news_filters']			= array('Filter','Bitte geben Sie die Filterwerte passend zu den Filterwerten in den Nachrichten-Beiträgen an und vergeben Sie eine Bezeichnung');
$GLOBALS['TL_LANG']['tl_module']['news_sysfilter']			= array('Filterung auf Systemebene','Die Filterung geschieht in der Datenbank-Abfrage und ist auch Paginations-sicher.');
$GLOBALS['TL_LANG']['tl_module']['news_portfoliolistModule'] = array('Portfolio-Liste-Modul','Bitte wählen Sie das Portfolio-Liste-Modul, das gefiltert werden soll.');
$GLOBALS['TL_LANG']['tl_module']['news_filter_multiple'] 	= array('Mehrfachauswahl erlauben','Bitte wählen Sie hier, wenn mehrere Filterwerte erlaubt sein sollen.');
$GLOBALS['TL_LANG']['tl_module']['sorting'] 				= 'Sortierindex';
$GLOBALS['TL_LANG']['tl_module']['date'] 					= 'Datum';
$GLOBALS['TL_LANG']['tl_module']['author'] 					= 'Autor';