<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2024
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_news']['pastenew'] = array('Create new element on top','Create new element after element ID %s');
$GLOBALS['TL_LANG']['tl_news']['pasteafter'] = array('Paste on top','Paste after element ID %s');