<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2022
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_settings']['pct_license_log'] 		= array('Log license requests','License requests will be logged in the system log.');
$GLOBALS['TL_LANG']['tl_settings']['pct_license_suffixes'] 	= array('Custom domain suffix resolution','Please provide duplicate domain suffixes so the domain name/stem can be validated. (Only required if the domain has multiple endings, e.g. mydomain.com.eu)');
$GLOBALS['TL_LANG']['tl_settings']['contentelementset_export']	= array('Export content elements as sets','Adds the export as content element set button to the multiple edit function for content elements (admins only)');

/**
 * Legends
 */
$GLOBALS['TL_LANG']['tl_settings']['pct_theme_settings_legend'] 	= 'Theme - settings';