<?php 
/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2013 
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['page_import']['import_select']		= array('Choose template','Please choose the template you want to import.');

/**
 * Labels
 */
$GLOBALS['TL_LANG']['page_import']['import_value'] 	= 'Start import';

/**
 * Texts
 */
$GLOBALS['TL_LANG']['page_import']['headline']				= 'Import our templates';
$GLOBALS['TL_LANG']['page_import']['headline_success']		= 'Import done:';
$GLOBALS['TL_LANG']['page_import']['error'] 				= 'NOT IMPORTED "%s" (A unqiue field "%s" with the value "%s" already exists in table "%s"';
$GLOBALS['TL_LANG']['page_import']['done'] 					= 'All templates already exist';