<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2014
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['module_id']['pagebreak'][0] 	= 'CustomCatalog-Liste Modul wählen.';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['module_id']['pagebreak'][1] 	= 'Wählen Sie hier das CustomCatalog-Liste Modul, auf das der Seitenumbruch-Filter angewendet werden soll.';