<?php
/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2013 
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['sortBy'] 	= array('Sortierung nach','Bitte wählen Sie eine Sortierreihenfolge aus.');
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options']['gallery'] = array('Attribut-Optionen','Wählen Sie welche zusätzlichen Optionen dargestellt werden sollen.');
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options']['gallery']['alt'] 				= 'Alternativer Text';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options']['gallery']['title'] 			= 'Titel';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options']['gallery']['size'] 			= 'Bildbreite und Bildhöhe';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options']['gallery']['imagemargin'] 		= 'Bildabstand';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options']['gallery']['fullsize'] 		= 'Großansicht/Neues Fenster';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options']['gallery']['caption'] 			= 'Bildunterschrift';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options']['gallery']['perPage'] 			= 'Elemente pro Seite';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options']['gallery']['perRow'] 			= 'Vorschaubilder pro Reihe';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options']['gallery']['numberOfItems']	= 'Gesamtzahl der Bilder';
