<?php
/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2013 
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['include_type'] 				= array('Include type','Choose the type of include element');
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['include_type']['article'] 	= 'Article';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['include_type']['module'] 	= 'Module';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['include_type']['form'] 		= 'Formular';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['include_type']['content'] 	= 'Content element';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['include_item']				= array('Include element','Choose an include element. Leave blank to make your selection in the entry.');