<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2014
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['MOD']['pct_customelements_plugin_customcatalog'] 	= 'PCT CustomCatalog '.PCT_CUSTOMCATALOG_VERSION.' (PCT CustomElement Plugin)';
$GLOBALS['TL_LANG']['FMD']['pct_customcatalog_node'] 					= 'CustomCatalog';
$GLOBALS['TL_LANG']['FMD']['customcataloglist'][0]						= 'CustomCatalog-Liste';
$GLOBALS['TL_LANG']['FMD']['customcataloglist'][1]						= 'Erstellt eine Liste an Datensätzen aus einem Custom Catalog.';
$GLOBALS['TL_LANG']['FMD']['customcatalogreader'][0]					= 'CustomCatalog-Leser';
$GLOBALS['TL_LANG']['FMD']['customcatalogreader'][1]					= 'Erstellt ein Leser-Modul für CustomCatalog Einträge';
$GLOBALS['TL_LANG']['FMD']['customcatalogfilter'][0]					= 'CustomCatalog-Filter';
$GLOBALS['TL_LANG']['FMD']['customcatalogfilter'][1]					= 'Erstellt ein Filter-Modul für CustomCatalog Einträge';
$GLOBALS['TL_LANG']['FMD']['customcatalog_apistarter'][0]				= 'CustomCatalog-API-Starter';
$GLOBALS['TL_LANG']['FMD']['customcatalog_apistarter'][1]				= 'Erstellt ein API-Starter-Modul für CustomCatalog APIs, das diese aus dem Frontend heraus gestartet werden können.';