<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2014
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['isSelector'][0]							= 'Kontroll-Checkbox';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['isSelector'][1]							= 'Dieses Feld als Kontroll-Checkbox für weitere Attribute/Felder nutzen.';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['subpalettes']['attribute_mode'][0]		= 'Kontrollierte Felder';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['subpalettes']['attribute_mode'][1]		= 'Wählen Sie die Attribute / Felder, die erst durch setzen der Checkbox angezeigt werden.';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['subpalettes']['group_mode'][0]			= 'Kontrollierte Paletten';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['subpalettes']['group_mode'][1]			= 'Wählen Sie die Paletten aus';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['be_exclude'][0]		= 'Für Gruppenrechte bereitstellen';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['be_exclude'][1]		= 'Blendet das Feld für reguläre Benutzer aus. Kann in den Gruppeneinstellungen festgelegt werden (erlaubte Felder).';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['be_filter'][0]		= 'Backend-Filter';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['be_filter'][1]		= 'Fügt das Feld dem Filtermenü hinzu (vgl. "Datensätze sortieren" -> "Paneellayout").';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['be_search'][0]		= 'Backend-Suche';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['be_search'][1]		= 'Fügt das Feld dem Suchmenü hinzu (vgl. "Datensätze sortieren" -> "Paneellayout").';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['be_sorting'][0]		= 'Backend-Sortierung';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['be_sorting'][1]		= 'Fügt das Feld dem Sortiermenü hinzu (vgl. "Datensätze sortieren" -> "Paneellayout").';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['isToggler'][0]		= 'Ist Listen-Button';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['isToggler'][1]		= 'Wählen Sie hier, wenn die Checkbox als Button in der Listenansicht schaltbar sein soll.';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['icon'][0]			= 'Icon auswählen (aktiver Zustand)';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['icon'][1]			= 'Wählen Sie hier das Icon aus.';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['icon_off'][0]		= 'Icon auswählen (Deaktivierter Zustand)';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['icon_off'][1]		= 'Wählen Sie hier das Icon aus.';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['eval_unique'][0]		= 'Feldwert ist einzigartig';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['eval_unique'][1]		= 'Legt fest, dass ein Feldwert nur einmal vorkommen darf.';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['include_type']['catalog'] = 'CustomCatalog';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options']['include'][0] = 'Darstellungs-Optionen';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options']['include'][1] = 'Wählen Sie die Darstellung des Feldes. Standard: Select-Feld';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options']['include']['tags'] = 'Tags';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options']['include']['checkbox'] = 'Checkbox';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options']['include']['radio'] = 'Radio-Button (Einzelauswahl)';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options']['alias'][0] = 'Alias-Einstellungen';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options']['alias'][1] = 'Wählen Sie eine erweiterte Alias-Generierungs-Option.';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options']['alias']['lower'] = 'Kleinbuchstaben';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options']['alias']['stnd'] = 'Umlaute ersetzen';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options']['alias']['stnd_lower'] = 'Umlaute ersetzen, Kleinbuchstaben';