<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2014
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['tl_pct_customelement_group']['selector'][0]					= 'Gruppenset';
$GLOBALS['TL_LANG']['tl_pct_customelement_group']['selector'][1]					= 'Hier können Sie die aktuelle Gruppen einem Gruppenset zu ordnen.';

/**
 * Panels
 */
$GLOBALS['TL_LANG']['tl_pct_customelement_group']['panel']['groupset'] = array('Palettensammlung','');
$GLOBALS['TL_LANG']['tl_pct_customelement_group']['panel']['groupset']['new'] = '-- Neue Sammlung aus aktiver Liste --';
$GLOBALS['TL_LANG']['tl_pct_customelement_group']['panel']['groupset']['edit'] = '-- Sammlungen bearbeiten --';
$GLOBALS['TL_LANG']['tl_pct_customelement_group']['panel']['groupset']['default'] = 'Standard';
$GLOBALS['TL_LANG']['tl_pct_customelement_group']['panel']['groupset']['label'] = ' (%s Attr. in %s Gruppen)';

/**
 * Buttons
 */
$GLOBALS['TL_LANG']['tl_pct_customelement_group']['groupset']			= array('Neue Sammlung','Eine neue Gruppensammlung aus den aktuellen Gruppen erstellen.');