<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2014
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['tl_pct_customcatalog']['title'][0]						= 'Name';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['title'][1]						= 'Geben Sie einen Namen für diese Konfiguration ein.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['tableName'][0]					= 'Tabellenname';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['tableName'][1]					= 'Wählen Sie einen Tabellenname.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['useTitleAsName'][0]			= 'Den Namen der Konfiguration als Backend-Namen benutzen.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['useTitleAsName'][1]			= 'Wählen Sie hier um den Namen der Konfiguration as Namen des Backend-Moduls zu benutzen. (Standard ist der Name des CustomElements)';
// settings
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['mode'][0]						= 'Betriebsmodus';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['mode'][1]						= 'Wählen Sie die Betriebsform der Tabelle. Standard: Alleinstehen';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['mode']['new']					= 'Neue Tabelle';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['mode']['existing']				= 'Existierende Tabelle';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['moreTables'][0]				= 'Weitere verknüpfte Tabellen';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['moreTables'][1]				= 'Wählen Sie weitere Tabellen, die von dem Backend-Modul zugänglich sind.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['tables'][0]					= 'Tabellen';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['tables'][1]					= 'Wählen Sie weitere verknüpfte Tabellen.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['cTables'][0]					= 'Kindtabellen';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['cTables'][1]					= 'Wählen Sie weitere Kind-Tabellen aus. Referenz: (table.id = ctable.pid) ';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['pTable'][0]					= 'Elterntabelle';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['pTable'][1]					= 'Wählen Sie die Elterntabelle aus. Referenz: (table.pid = ptable.id)';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['existingTable'][0]				= 'Existierende Tabelle';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['existingTable'][1]				= 'Wählen Sie hier, wenn Sie eine existierende Tabelle als Kindtabelle nutzen wollen.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['isManageable'][0]				= 'Tabelle verwalten';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['isManageable'][1]				= 'Wählen Sie hier, um CustomCatalogs das Verwalten der existierenden Tabelle zu ermöglichen. Es werden neue Felder angelegt/gelöscht etc. Die DCA Konfiguration der Tabelle wird dabei berücksichtigt (mit Vorsicht zu benutzen).';
#$GLOBALS['TL_LANG']['tl_pct_customcatalog']['isManageable']['protected'][0]		= 'Nur eigene Felder verwalten';
#$GLOBALS['TL_LANG']['tl_pct_customcatalog']['isManageable']['protected'][1]		= 'Wählen Sie hier damit die existierende Tabelle nur durch CustomCatalog eigene Felder erweitert wird.';

// integration
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['beSection'][0]					= 'Backend-Module-Bereich';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['beSection'][1]					= 'Wählen Sie den Bereich in der linken Spalte (Backend-Module), in dem das Element angezeigt werden soll.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['injectBelow'][0]				= 'Einfügen nach...';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['injectBelow'][1]				= 'Wählen Sie das Module nachdem das Element angezeigt werden soll. (leer lassen für oben einfügen).';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['injectBelow']['__beforeAll__']	= '(Oben einfügen)';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['injectBelow']['__belowAll__']	= '(Unten einfügen)';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['showMenu'][0]					= 'Backend-Untermenü generieren';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['showMenu'][1]					= 'Wählen Sie hier um das Untermenu zu erstellen.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['newSection'][0]				= 'Neuen Backend-Bereich erstellen.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['newSection'][1]				= 'Wählen Sie um einen neuen Backend-Bereich für dieses Element zu erstellen.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['sectionName'][0]				= 'Name';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['sectionName'][1]				= 'Geben Sie Ihrem neuen Backend-Bereich einen Namen.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['sectionAlias'][0]				= 'Alias';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['sectionAlias'][1]				= 'Der Alias des Backend-Bereichs. Wird in $GLOBALS["BE_MOD"][...] verwendet und wird auch für Übersetzungen benötigt. $GLOBALS["TL_LANG"]["BE_MOD"][...]';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['icon'][0]						= 'Backend-Icon';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['icon'][1]						= 'Wählen Sie das Icon aus, das neben dem Modulnamen angezeigt wird. Empfohlene Größe: 16x16px';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['active'][0]					= 'Aktivieren';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['active'][1]					= 'Diese Konfiguration aktivieren.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['publishedField'][0]			= 'Veröffentlichen Checkbox';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['publishedField'][1]			= 'Wählen Sie das Checkbox Attribute, das den veröffentlichen Status des Datensatzes steuert.';
// list
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['list_mode'][0]					= 'Sortierungsmodus';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['list_mode'][1]					= 'Wählen Sie die Art der Sortierung der Datensätze. Siehe: <a href="https://contao.org/de/manual/3.0/data-container-arrays.html#tabellenkonfiguration">Contao-Handbuch</a>';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['list_mode']['ref'][0]			= '0 Keine Sortierung';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['list_mode']['ref'][1]			= '1 Sortierung nach einem festen Feld';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['list_mode']['ref'][2]			= '2 Sortierung nach einem variablen Feld';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['list_mode']['ref'][3]			= '3 Sortierung anhand der Elterntabelle';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['list_mode']['ref'][4]			= '4 Darstellung der Kinddatensätze eines Elterndatensatzes (vgl. Stylesheets-Modul)';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['list_mode']['ref'][5]			= '5 Darstellung als Baum (vgl. Seitenstruktur) mit Verschachtelung';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['list_mode']['ref']['5.1']		= '5.1 Darstellung als Baum (vgl. Seitenstruktur) ohne Verschachtelung';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['list_mode']['ref'][6]			= '6 Sortierung der Kinddatensätze anhand eines Baumes (vgl. Artikelverwaltung)';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['list_headerFields'][0]			= 'Header-Felder';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['list_headerFields'][1]			= 'Eines oder mehrere Felder, die im Header des Parent View angezeigt werden (nur Sortierungsmodus 4). Hinweis: <a href="https://contao.org/de/manual/3.0/data-container-arrays.html#tabellenkonfiguration">Contao-Handbuch</a>';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['list_fields'][0]				= 'Standard-Sortierfelder';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['list_fields'][1]				= 'Eines oder mehrere Felder, anhand derer die Tabelle sortiert wird. Standard ist nach Datansatz-ID. Hinweis: <a href="https://contao.org/de/manual/3.0/data-container-arrays.html#tabellenkonfiguration">Contao-Handbuch</a>';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['list_flag'][0]					= 'Sortierlogik';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['list_flag'][1]					= 'Wählen Sie die Sortierlogik der Datensätze aus. Standard ist nach Datansatz-ID. Hinweis: <a href="https://contao.org/de/manual/3.0/data-container-arrays.html#tabellenkonfiguration">Contao-Handbuch</a>';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['list_flag']['ref'][0]			= '0 Standard, Sortierung nach Datansatz-ID';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['list_flag']['ref'][1]			= '1 Aufsteigende Sortierung nach Anfangsbuchstabe';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['list_flag']['ref'][2]			= '2 Absteigende Sortierung nach Anfangsbuchstabe';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['list_flag']['ref'][3]			= '3 Aufsteigende Sortierung nach den ersten beiden Buchstaben';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['list_flag']['ref'][4]			= '4 Absteigende Sortierung nach den ersten beiden Buchstaben';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['list_flag']['ref'][5]			= '5 Aufsteigende Sortierung nach Tag';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['list_flag']['ref'][6]			= '6 Absteigende Sortierung nach Tag';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['list_flag']['ref'][7]			= '7 Aufsteigende Sortierung nach Monat';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['list_flag']['ref'][8]			= '8 Absteigende Sortierung nach Monat';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['list_flag']['ref'][9]			= '9 Aufsteigende Sortierung nach Jahr';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['list_flag']['ref'][10]			= '10 Absteigende Sortierung nach Jahr';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['list_flag']['ref'][11]			= '11 Aufsteigende Sortierung';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['list_flag']['ref'][12]			= '12 Absteigende Sortierung';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['list_panelLayout'][0]			= 'Panellayout';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['list_panelLayout'][1]			= '<b>search</b> zeigt das Suchfeld an<br>sort zeigt das Sortiermenü an<br><b>filter</b> zeigt die Filtermenüs an<br><b>limit</b> zeigt das Limitmenü an.<br> Trennen Sie die Menüs mit Komma (= Abstand) oder Strichpunkt (= neue Zeile), also z.B. sort,filter;search,limit.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['list_operations'][0]			= 'Buttons';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['list_operations'][1]			= 'Wählen Sie die Buttons aus, die zu jedem Datensatz angezeigt werden. Leer für Standard (edit,copy,delete,show)';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['list_operations']['edit']		= 'Bearbeiten (edit)';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['list_operations']['copy']		= 'Kopieren (copy)';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['list_operations']['cut']		= 'Verschieben (cut)';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['list_operations']['show']		= 'Informationen (show)';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['list_operations']['delete']	= 'Löschen (delete)';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['list_operations']['toggle']	= 'Veröffentlichen (toggle)';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['list_operations']['copyChilds']= 'Mit Kindelementen kopieren (copyChilds)';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['list_operations']['langswitch']= 'Spracheintrag-Auswahl (langswitch)';
// output
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['aliasField'][0]				= 'Alias-Feld/Attribut';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['aliasField'][1]				= 'Wählen Sie das Alias-Attribut, das anstelle der ID zum Generieren der Frontend-URL genutzt werden soll.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['sitemapField'][0]				= 'Sitemap/Such-Feld/Attribut';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['sitemapField'][1]				= 'Wählen Sie das Attribute, das als Quelle für die Sitemap- und Suchindex-URL genutzt werden soll.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['jumpTo'][0]					= 'Weiterleitungsseite';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['jumpTo'][1]					= 'Wählen Sie eine CustomCatalog-Leser-Seite aus, zu der Besucher weitergeleiter werden, wenn ein Katalog-Eintrag direkt verlinkt wird. Die Auswahl ist Vorraussetzung für die Integration in den DCA-Picker.';
// label
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['label_overwrite'][0]			= 'Label-/Bezeichnungen überschreiben';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['label_overwrite'][1]			= 'Wählen Sie hier wenn Sie eigene Bezeichnungen der Datensätze in der Listendarstellung erstellen wollen';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['label_html'][0]				= 'Label-Aufbau (HTML ist erlaubt)';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['label_html'][1]				= 'Sie können inserttags in Form von {{attributeAlias}} verwenden, um einen Feldwert anzeigen zu lassen. z.B. {{mein-text}} oder {{mein-bild?width=50&height=50&mode=center_center}}';
// languages
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['multilanguage'][0]				= 'Mehrsprachigkeit aktivieren';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['multilanguage'][1]				= 'Wählen Sie hier, wenn Sie die Mehrsprachigkeit aktivieren wollen';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['languages'][0]					= 'Sprachen';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['languages'][1]					= 'Wählen Sie die zusätzlichen Sprachen aus.';
// comments
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['allowComments'][0]				= 'Kommentare erlauben';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['allowComments'][1]				= 'Wählen Sie um Kommentare zu erlauben. Contaos Kommentar-Erweiterung muss aktiv sein.';
// restrictions
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['restrictCte'][0]				= 'Inhaltselemente verbieten';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['restrictCte'][1]				= 'Wählen Sie hier, wenn Sie die Auswahl von Inhaltselementen für bestimmte Elemente verbieten möchten.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['restrictedCte'][0]				= 'Inhaltselemente';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['restrictedCte'][1]				= 'Wählen Sie die Inhaltselemente aus, die NICHT zur Auswahl stehen sollen.';


/**
 * Legends
 */
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['customcatalog_legend']			= 'Einstellungen: Eigenes Backend-Modul (Plugin: CustomCatalog)';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['title_legend']					= 'Titel und Bezeichnung';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['expert_legend']				= 'Experten-Einstellungen';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['settings_legend']				= 'Integrations-Einstellungen';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['template_legend']				= 'Template-Einstellungen';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['protected_legend']				= 'Zugriffsschutz';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['layout_legend']				= 'Darstellungs-Einstellungen';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['integration_legend']			= 'Backend-Integrations-Einstellungen';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['list_legend']					= 'Listen- und Darstellungs-Einstellungen';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['label_legend']					= 'Label/Bezeichnungs-Einstellungen';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['language_legend']				= 'Sprachen-Einstellungen';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['output_legend']				= 'Ausgabe-Einstellungen';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['config_legend']				= 'Konfiguration';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['comments_legend']				= 'Kommentar-Einstellungen';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['restriction_legend']				= 'Freigabe-Einstellungen';


/**
 * Buttons
 */
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['new']        					= array('Neue Konfiguration', 'Eine neue Konfiguration anlegen.');
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['edit'][0]						= 'Konfiguration bearbeiten';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['edit'][1]						= 'Konfiguration ID %s bearbeiten';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['copy'][0]						= 'Element kopieren';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['copy'][1]						= 'Element ID %s kopieren';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['cut'][0]						= 'Element verschieben';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['cut'][1]						= 'Element ID %s verschieben';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['copyChilds'][0]				= 'Element inklusive Kindelemente kopieren';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['copyChilds'][1]				= 'Element ID %s inklusive Kindelemente kopieren';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['delete'][0]					= 'Element entfernen';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['delete'][1]					= 'Element ID %s entfernen';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['show'][0]						= 'Details';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['show'][1]						= 'Details des Elements ID %s anzeigen';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['edit_config'][0] 				= 'Konfiguration bearbeiten';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['edit_config'][1] 				= 'Konfiguration ID %s bearbeiten';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['toggle'][0]					= 'Veröffentlichen';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['toggle'][1]					= 'Die Sichtbarkeit des Elements %s ändern';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['filterset'][0]					= 'Filter bearbeiten';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['filterset'][1]					= 'Filter für Konfiguration ID %s bearbeiten';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['api'][0]						= 'API Anbindungen bearbeiten';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['api'][1]						= 'API Anbindungen für Konfiguration ID %s bearbeiten';

/**
 * DB Update Backend page
 */
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['be_page_db_update']['headline'] 				= 'Datenbank-Update-Helfer';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['be_page_db_update']['headline_clear_cache'] 	= 'Internen Cache bzw. Symphony Cache leeren';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['be_page_db_update']['headline_db_update'] 		= 'Datenbank-Update wird ausgeführt...';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['be_page_db_update']['headline_done']	 		= 'Datenbank-Update abgeschlossen';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['be_page_db_update']['info']					= 'Datenbank-Änderung erkannt: %s';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['be_page_db_update']['info_clear_cache']		= 'Bitte warten Sie bis der interne Cache bzw. Symphony Cache geleert ist. <br> Nach Fertigstellung werden Sie weitergeleitet...';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['be_page_db_update']['info_db_update']			= 'Tabellen: %s';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['be_page_db_update']['info_done']				= 'Geänderte Tabellen: %s';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['be_page_db_update']['info_empty']				= 'Keine Datenbank-Änderung nötig.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['be_page_db_update']['errors']					= 'Es sind Fehler aufgetreten: <br> %s';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['be_page_db_update']['submit']					= 'Ausführen';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['be_page_db_update']['legend_tables'] 			= 'Wählen Sie die Tabellen aus.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog']['be_page_db_update']['subheadline_statements']	= 'Änderungen (Ausgeführte SQL-Befehle) anzeigen:';