<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2016
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['type'][0]					= 'API-Schnittstelle';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['type'][1]					= 'Wählen Sie eine der verfügbaren API-Schnittstellen aus';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['type']['default']			= 'Standard';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['published'][0]				= 'Aktivieren';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['published'][1]				= 'Die API-Schnittstelle für die Verwendung bereitstellen.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['title'][0]					= 'Titel';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['title'][1]					= 'Geben Sie dem API-Datensatz einen Titel.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['description'][0]			= 'Beschreibung';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['description'][1]			= 'Geben Sie dem API-Datensatz eine Beschreibung.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['isPublished'][0]			= 'Nur veröffentlicht';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['isPublished'][1]			= 'Nur veröffentlichte Daten einbeziehen. Ein Veröffentlichen Feld muss in der Tabellenkonfiguration angegeben sein.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['mode'][0]					= 'Modus';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['mode'][1]					= 'Wählen Sie den Modus dieser Anbindung';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['mode']['standard']			= 'Standard';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['mode']['import']			= 'Import';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['mode']['export']			= 'Export';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['cronjob'][0]				= 'Cronjob aktivieren';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['cronjob'][1]				= 'Wählen Sie hier um einen Backend Cronjob für die Anbindung zu aktiveren.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['cron'][0]					= 'Cronjob';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['cron'][1]					= 'Wählen Sie die Art des Cronjobs.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['cron']['weekly']			= 'Wöchentlich';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['cron']['daily']			= 'Täglich';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['cron']['hourly']			= 'Stündlich';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['cron']['minutely']			= 'Je Minute';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['source'][0]				= 'Quelle';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['source'][1]				= 'Wählen Sie die Quelle der Datenübermittlung';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['source']['table']			= 'Tabelle';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['source']['file']			= 'Datei';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['source']['php']			= 'PHP-Array aus Template';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['source']['template']		= 'PHP-Array aus Template';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['tableSRC'][0]				= 'Tabelle';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['tableSRC'][1]				= 'Wählen Sie die Tabelle aus.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['singleSRC'][0]				= 'Dateiauswahl';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['singleSRC'][1]				= 'Wählen Sie die Datei aus.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['hookSRC'][0]				= 'Hook-Funktion auswählen';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['hookSRC'][1]				= 'Wählen sie die Callback-Funktion aus. Es werden folgende Parameter übergeben: myFunction($arrSet, $strTable, $objApi)';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['templateSRC'][0]			= 'Template-Datei auswählen';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['templateSRC'][1]			= "Bitte wählen Sie die Template-Datei aus, die einen PHP Array mit dem Variablennamen dieser Tabellenkonfiguration enthält. Beispiel: \$\my_cc_table = array('id'=>1,...). Die Template Dateien müssen mit api_ beginnen.";
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['uniqueSource'][0]			= 'Schlüsselfeld in Quelle';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['uniqueSource'][1]			= 'Wählen Sie das einzigartige Schlüsselfeld der Quelle.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['uniqueTarget'][0]			= 'Schlüsselfeld';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['uniqueTarget'][1]			= 'Wählen Sie das einzigartige Schlüsselfeld dieser CC-Tabellen-Konfiguration.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['allowUpdate'][0]			= 'Einträge updaten';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['allowUpdate'][1]			= 'Erlaubt das Überschreiben bestehender Datensätze anhand der Schlüsselfelder.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['allowInsert'][0]			= 'Neue Einträge anlegen';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['allowInsert'][1]			= 'Erlaubt das Anlegen neuer Einträge, wenn diese in der aktuellen Tabelle nicht existieren.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['allowDelete'][0]			= 'Einträge löschen';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['allowDelete'][1]			= 'Einträge löschen, die nicht in der Quelle existieren.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['delimiter'][0]				= 'Trennzeichen';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['delimiter'][1]				= 'Wählen Sie das Feld-Trennzeichen.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['delimiter']['comma']		= 'Komma [,]';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['delimiter']['semicolon']	= 'Semikolon [;]';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['delimiter']['tab']			= 'Tabulator [-]';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['filenameLogic'][0]			= 'Dateibezeichnung';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['filenameLogic'][1]			= 'Geben Sie einen Dateinamen an. Inserttags sind erlaubt z.b. export_{{table}}_{{date::U}} = export_MEINE-TABELLE_12345678. Gleiche Dateinamen werden überschrieben.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['sendToBrowser'][0]			= 'An Browser senden';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['sendToBrowser'][1]			= 'Die Datei nach dem Erstellen direkt zum Download bereitgeben und an den Browser übermitteln.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['path'][0]					= 'Zielpfad';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['path'][1]					= 'Wählen Sie den Zielpfad zum Speichern der Datei. (Standard: /files)';


$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['target'][0]				= 'Ziel';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['target'][1]				= 'Wählen Sie das Ziel der Datenübermittlung';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['target']['hook']			= 'Hook-Callback-Funktion';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['target']['template']		= 'Template-Export';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['target']['csv']			= 'CSV-Export';

$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['purgeTable'][0]			= 'Tabelle vor Import leeren';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['purgeTable'][1]			= 'Leer die Tabelle bevor der Import ausgeführt wird.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['backup'][0]				= 'Backup / Wiederherstellungspunkt anlegen';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['backup'][1]				= 'Wählen Sie hier, wenn vor dem Ausführen ein Backup der aktuellen Tabelle angelegt werden soll. Das Backup wird in tl_undo erstellt.';

$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['maxRange'][0]				= 'Maximale Anzahl an Einträgen';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['maxRange'][1]				= 'Wählen Sie die maximale Anzahl an Einträgen, die gemeinsam verarbeitet werden sollen. (Standard: 1). Alle = 0';


/**										  
 * Legends								  
 */										  
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['title_legend']				= 'API-Auswahl';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['settings_legend']			= 'API-Aufgaben-Einstellungen';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['cronjob_legend']			= 'Cronjob-Einstellungen';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['expert_legend']			= 'Experten-Einstellungen';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['source_legend']			= 'Datenquellen-Einstellungen';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['update_legend']			= 'Update-Regeln-Einstellungen';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['data_legend']				= 'Daten-Einstellungen';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['backup_legend']			= 'Backup-Einstellungen';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['resources_legend']			= 'Ressourcen-Einstellungen';

										  
/**										  
 * Buttons								  
 */										  
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['new'][0] 					= 'Neue API-Anbindung hinzufügen';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['new'][1] 					= 'Erstellen Sie eine neue API-Verbindung';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['job'][0] 					= 'API-Aufgaben bearbeiten';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['job'][1] 					= 'API-Aufgaben von Anbindung %s bearbeiten';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['edit'][0] 					= 'API-Anbindung bearbeiten';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['edit'][1] 					= 'API-Anbindung %s bearbeiten';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['copy'][0] 					= 'API-Anbindung duplizieren';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['copy'][1] 					= 'API-Anbindung %s duplizieren';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['cut'][0] 					= 'API-Anbindung verschieben';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['cut'][1] 					= 'API-Anbindung %s verschieben';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['delete'][0] 				= 'API-Anbindung löschen';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['delete'][1] 				= 'API-Anbindung %s löschen';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['toggle'][0] 				= 'Aktiv';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['toggle'][1] 				= 'API-Anbindung %s aktivieren/deaktivieren';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['history'][0] 				= 'Verlauf und Wiederherstellung';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['history'][1] 				= 'Verlauf und Wiederherstellung von Anbindung %s anzeigen';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['run'][0] 					= 'Ausführen';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['run'][1] 					= 'Aufgaben von Anbindung %s ausführen';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['ready'][0] 				= 'Ausführung vorbereiten';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['ready'][1] 				= 'Ausführung der Aufgaben von Anbindung %s vorbereiten';


/**
 * API Backend page
 */
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['be_page_api']['headline']						= 'API Anbindung %s ausführen';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['be_page_api']['headline_summary']				= 'Zusammenfassung API Anbindung %s';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['be_page_api']['subheadline_loading']			= 'Daten werden verarbeitet...';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['be_page_api']['subheadline_complete']			= 'Datenverarbeitung abgeschlossen.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['be_page_api']['subheadline_import_running']	= 'Import wird ausgeführt...';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['be_page_api']['subheadline_import_complete']	= 'Import abgeschlossen.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['be_page_api']['subheadline_errors']			= 'Bei der Ausführung wurden Fehler entdeckt. Aktiveren Sie den Contao Debug-Modus in den Systemeinstellungen, um System-Logs zu speichern oder nutzen Sie die Browser-Console bei Ajax Befehlen.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['be_page_api']['run_headline']					= 'Jobs von API Anbindung %s ausführen.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['be_page_api']['ready_info']					= '<span class="tl_green">Der API Auftrag %s kann gestartet werden.</span><br>Der Auftrag beinhaltet %s Aufgabe(n).';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['be_page_api']['submit_run'] 					= 'Ausführen';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['be_page_api']['empty_jobs'] 					= 'Keine aktiven Jobs gefunden!';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['be_page_api']['submit_abort'] 					= 'Abbrechen';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['be_page_api']['submit_summary'] 				= 'Zusammenfassung';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['be_page_api']['submit_complete'] 				= 'Fertigstellen';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['be_page_api']['ajax_complete_console_log'] 	= 'Processing data for CustomCatalog API %s completed';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['be_page_api']['file_created'] 					= 'Datei <span class="tl_green">%s</span> erstellt in %s';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['be_page_api']['process_all_data_at_once'] 		= 'Alle Daten werden auf einmal verarbeiten. Maximal Anzahl an Einträgen ist 0 oder größer der Anzahl an Daten.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['be_page_api']['backupCreated'] 				= 'Backup von Tabelle %s wurde erstellt in tl_undo.id=%s';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['be_page_api']['purgedTable'] 					= 'Tabelle %s wurde geleert.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['be_page_api']['headline_backup']				= 'Backup:';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['be_page_api']['headline_purgeTable']			= 'Tabelle leeren:';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['be_page_api']['readyToRock']					= 'Alles bereit.';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['be_page_api']['no_summary']					= 'Keine Daten für eine Zusammenfassung';


/**
 * API Report (see report array for keys)
 */
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['api_report']['headline']								= '<h3>Report:</h3>';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['api_report']['data_index']								= 'Report (data-index: %s)';

$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['api_report']['endTime']['label']						= 'Endzeit';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['api_report']['endTime']['format']						= 'd.m.Y H:i';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['api_report']['endTime']['type']						= 'date';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['api_report']['executionTime']['label'] 				= 'Prozesszeit in ms';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['api_report']['startTime']['label'] 					= 'Startzeit';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['api_report']['startTime']['type'] 						= 'date';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['api_report']['startTime']['format']					= 'd.m.Y H:i';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['api_report']['endTime']['type']						= 'date';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['api_report']['errors'] ['label']						= 'Fehler';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['api_report']['completedWithErrors']['label']			= 'Fertiggestellt mit Fehlern';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['api_report']['completedWithErrors']['type']			= 'boolean';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['api_report']['complete']['label']						= 'Fertiggestellt';
$GLOBALS['TL_LANG']['tl_pct_customcatalog_api']['api_report']['complete']['type']						= 'boolean';