<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2021
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */


$GLOBALS['TL_LANG']['PCT_FRONTEND_QUICKEDIT']['be_link'][0] = 'Show in backend';
$GLOBALS['TL_LANG']['PCT_FRONTEND_QUICKEDIT']['be_link'][1] = 'Show active selection in backend';
$GLOBALS['TL_LANG']['PCT_FRONTEND_QUICKEDIT']['themedesigner_active_error'] = 'Please deactivate the ThemeDesigner to use the frontend editing.';
$GLOBALS['TL_LANG']['PCT_FRONTEND_QUICKEDIT']['themedesigner_active_info'] = 'The frontend editing is disabled while the ThemeDesigner is in editing mode.';