<?php

// vendor/contao/core-bundle/contao/languages/de/exception.xlf
$GLOBALS['TL_LANG']['XPT']['error'] = 'Es ist ein Fehler aufgetreten';
$GLOBALS['TL_LANG']['XPT']['matter'] = 'Was ist das Problem?';
$GLOBALS['TL_LANG']['XPT']['howToFix'] = 'Wie kann ich das Problem lösen?';
$GLOBALS['TL_LANG']['XPT']['more'] = 'Weitere Informationen';
$GLOBALS['TL_LANG']['XPT']['hint'] = 'Legen Sie ein eigenes Twig-Template an, das das Template <em>%s</em> überschreibt, um diese Meldung anzupassen.';
$GLOBALS['TL_LANG']['XPT']['errorOccurred'] = 'Bei der Ausführung des Skriptes ist ein Fehler aufgetreten. Irgendetwas funktioniert nicht richtig.';
$GLOBALS['TL_LANG']['XPT']['errorFixOne'] = 'Öffnen Sie die aktuelle Log-Datei im Ordner <code>var/logs</code> und suchen Sie die zugehörige Fehlermeldung (normalerweise die letzte).';
$GLOBALS['TL_LANG']['XPT']['errorExplain'] = 'Die Skriptausführung wurde gestoppt, weil irgendetwas nicht korrekt funktioniert. Die eigentliche Fehlermeldung wird aus Sicherheitsgründen hinter dieser Meldung verborgen und findet sich in der aktuellen Log-Datei (siehe oben). Wenn Sie die Fehlermeldung nicht verstehen oder nicht wissen, wie das Problem zu beheben ist, besuchen Sie die <a href="%s" target="_blank" rel="noreferrer noopener">Contao-Supportseite</a>.';
$GLOBALS['TL_LANG']['XPT']['requestToken'] = 'Ungültiges Anfrage-Token';
$GLOBALS['TL_LANG']['XPT']['invalidToken'] = 'Das Request-Token konnte nicht validiert werden.';
$GLOBALS['TL_LANG']['XPT']['tokenRetry'] = 'Bitte <a href="javascript:window.location.href=window.location.href">klicken Sie hier</a> und versuchen Sie es erneut. Verwenden Sie nicht die Zurück-Schaltfläche Ihres Browsers.';
$GLOBALS['TL_LANG']['XPT']['tokenExplainOne'] = 'Der Fehler tritt bei einer POST-Anfrage ohne gültiges Request-Token auf. In Contao 2.10 wurde die Referer-Prüfung durch ein Request-Token-System ersetzt. Wenn das Problem anhält, verwenden Sie eventuell eine inkompatible Drittanbieter-Erweiterung oder haben Ihre Contao-Installation nicht vollständig aktualisiert.';
$GLOBALS['TL_LANG']['XPT']['tokenExplainTwo'] = 'Besuchen Sie die <a href="%s" target="_blank" rel="noreferrer noopener">Contao-Supportseite</a> für weitere Informationen.';
$GLOBALS['TL_LANG']['XPT']['unavailable'] = 'Dienst nicht verfügbar';
$GLOBALS['TL_LANG']['XPT']['maintenance'] = 'Die Webseite ist momentan nicht verfügbar. Bitte versuchen Sie es später noch einmal.';
$GLOBALS['TL_LANG']['XPT']['missingRouteParameters']['title'] = 'Frontend-URL kann nicht generiert werden';
$GLOBALS['TL_LANG']['XPT']['missingRouteParameters']['matter'] = 'Die URL konnte nicht generiert werden, weil die Route Parameter benötigt, die nicht zur Verfügung stehen. Es müssen zusätzliche Informationen (z. B. ein News-Alias) angegeben werden.';
$GLOBALS['TL_LANG']['XPT']['missingRouteParameters']['explain'] = 'Symfony-Routen können variable Parameter haben, die anhand regulärer Ausdrücke validiert werden. Die folgende Konfiguration konnte nicht aufgelöst werden:';
$GLOBALS['TL_LANG']['XPT']['missingRouteParameters']['path'] = 'Routen-Pfad';
$GLOBALS['TL_LANG']['XPT']['missingRouteParameters']['parameterName'] = 'Name';
$GLOBALS['TL_LANG']['XPT']['missingRouteParameters']['parameterRequirement'] = 'Bedingung (Regex)';
$GLOBALS['TL_LANG']['XPT']['missingRouteParameters']['parameterDefault'] = 'Standard-Wert';
$GLOBALS['TL_LANG']['XPT']['missingRouteParameters']['parameterEmpty'] = 'leer';

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2021
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
/**
 * Errors
 */
$GLOBALS['TL_LANG']['XPT']['pct_theme_updater']['unzip_error'] = 'Das Entpacken der Datei %s ist fehlgeschlagen.';
$GLOBALS['TL_LANG']['XPT']['pct_theme_updater']['zip_content_error'] = 'Pflichtinhalte (%s) in dem entpackten Verzeichnis nicht gefunden.';
$GLOBALS['TL_LANG']['XPT']['pct_theme_updater']['sql_not_found'] = 'SQL-Installations-Template nicht gefunden.';
$GLOBALS['TL_LANG']['XPT']['pct_theme_updater']['session_lost'] = 'Die Lizenz-Session ist abgelaufen. Bitte starten Sie die Installation erneut.';
$GLOBALS['TL_LANG']['XPT']['pct_theme_updater']['version_conflict'] = 'Bitte nutzen Sie Contaos LTS Versionen: 4.13 oder 5.3';
$GLOBALS['TL_LANG']['XPT']['pct_theme_updater']['memory_limit'] = 'Memory Limit (memory_limit) zu gering (%s). Min.: 512M';
$GLOBALS['TL_LANG']['XPT']['pct_theme_updater']['changelog_not_found'] = 'Aktuelle Theme-Version konnte nicht ermittelt werden. (/templates/changelog.txt nicht gefunden)';
$GLOBALS['TL_LANG']['XPT']['pct_theme_updater']['client_version_conflict'] = 'Eine neue Version des Theme-Updaters ist verfügbar. Bitte updaten Sie das Modul.';
$GLOBALS['TL_LANG']['XPT']['pct_theme_updater']['theme_compatiblity_conflict'] = 'Ihre aktuelle Theme Version %s ist nicht mit Contao %s kompatibel. Bitte updaten Sie das Theme von Contao %s aus und updaten Sie dann Contao.';
$GLOBALS['TL_LANG']['XPT']['pct_theme_updater']['theme_version_conflict'] = 'Contao %s wird nicht unterstützt. Unterstützte Contao Versionen: %s';
$GLOBALS['TL_LANG']['XPT']['pct_theme_updater']['min_theme_version'] = 'Die empfohlene Ausgangsversion für das Update ist EclipseX 4.0';

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2016
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
/**
 * Errors
 */
$GLOBALS['TL_LANG']['XPT']['pct_themer']['no_active_pages_found'] = 'Keine aktiven Seiten gefunden';
$GLOBALS['TL_LANG']['XPT']['pct_themer']['no_export_data'] = 'Keine Export-Daten in der Session gefunden. Bitte führen Sie die Datensammlung erneut durch.';
$GLOBALS['TL_LANG']['XPT']['pct_themer']['import_already_done'] = 'Import wurde bereits ausgeführt. Leeren Sie Ihre Benutzer-Session für einen erneuten Import.';
$GLOBALS['TL_LANG']['XPT']['pct_themer']['no_theme_record_selected'] = 'Bitte wählen Sie einen Theme-Datensatz als Ziel für Modul-Datensätze.';
$GLOBALS['TL_LANG']['XPT']['pct_themer']['pages_with_no_layout_save'] = 'Seitenstränge ohne Theme-Designer Speicherpunkt vorhanden.';

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2014
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
$GLOBALS['TL_LANG']['PCT_CUSTOMCATALOG']['XPT']['emptyDataContainerArray'] = 'Der DataContainer Array der Tabelle %s ist leer. Die weitere Ausführung des Scripts wurde gestoppt. Bitte überprüfen Sie Ihre Rückgabewerte.';
$GLOBALS['TL_LANG']['PCT_CUSTOMCATALOG']['XPT']['customelements_version_too_low'] = 'Ihre aktuelle CustomCatalog Version (%s) setzt CustomElements Version (%s) voraus. Aktuelle Version %s. Bitte updaten Sie CustomElements. Die Ausführung von CustomCatalog wurde gestoppt.';
$GLOBALS['TL_LANG']['PCT_CUSTOMCATALOG']['XPT']['reservedSqlWord'] = '"%s" ist ein reserviertes Wort. Bitte verwenden Sie einen anderen Ausdruck';
