<?php

// vendor/contao/news-bundle/contao/languages/de/tl_news_archive.xlf
$GLOBALS['TL_LANG']['tl_news_archive']['title']['0'] = 'Titel';
$GLOBALS['TL_LANG']['tl_news_archive']['title']['1'] = 'Bitte geben Sie den Archiv-Titel ein.';
$GLOBALS['TL_LANG']['tl_news_archive']['jumpTo']['0'] = 'Weiterleitungsseite';
$GLOBALS['TL_LANG']['tl_news_archive']['jumpTo']['1'] = 'Bitte wählen Sie die Nachrichtenleser-Seite aus, zu der Besucher weitergeleitet werden, wenn sie einen Beitrag anklicken.';
$GLOBALS['TL_LANG']['tl_news_archive']['protected']['0'] = 'Archiv schützen';
$GLOBALS['TL_LANG']['tl_news_archive']['protected']['1'] = 'Nachrichten nur bestimmten Mitgliedergruppen anzeigen.';
$GLOBALS['TL_LANG']['tl_news_archive']['groups']['0'] = 'Erlaubte Mitgliedergruppen';
$GLOBALS['TL_LANG']['tl_news_archive']['groups']['1'] = 'Diese Mitgliedergruppen können die Nachrichten des Archivs sehen.';
$GLOBALS['TL_LANG']['tl_news_archive']['tstamp']['0'] = 'Änderungsdatum';
$GLOBALS['TL_LANG']['tl_news_archive']['tstamp']['1'] = 'Datum und Uhrzeit der letzten Änderung';
$GLOBALS['TL_LANG']['tl_news_archive']['title_legend'] = 'Titel und Weiterleitung';
$GLOBALS['TL_LANG']['tl_news_archive']['protected_legend'] = 'Zugriffsschutz';
$GLOBALS['TL_LANG']['tl_news_archive']['feeds']['0'] = 'News-Feeds';
$GLOBALS['TL_LANG']['tl_news_archive']['feeds']['1'] = 'News-Feeds verwalten';
$GLOBALS['TL_LANG']['tl_news_archive']['new']['0'] = 'Neu';
$GLOBALS['TL_LANG']['tl_news_archive']['new']['1'] = 'Ein neues Nachrichtenarchiv erstellen';
$GLOBALS['TL_LANG']['tl_news_archive']['show'] = 'Details des Nachrichtenarchivs ID %s anzeigen';
$GLOBALS['TL_LANG']['tl_news_archive']['edit'] = 'Nachrichtenarchiv ID %s bearbeiten';
$GLOBALS['TL_LANG']['tl_news_archive']['children'] = 'Beiträge des Nachrichtenarchivs ID %s bearbeiten';
$GLOBALS['TL_LANG']['tl_news_archive']['copy'] = 'Nachrichtenarchiv ID %s duplizieren';
$GLOBALS['TL_LANG']['tl_news_archive']['delete'] = 'Nachrichtenarchiv ID %s löschen';

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2014
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_news_archive']['manualSorting'] = array('Manuelles Sortierungen', 'Wählen Sie hier um das manuelle Sortieren von Einträgen in dem Nachrichten-Archiv zu aktivieren.');
$GLOBALS['TL_LANG']['tl_news_archive']['pasteafter'] = array('Oben einfügen', 'Nach dem Inhaltselement ID %s einfügen');
$GLOBALS['TL_LANG']['tl_news_archive']['pastenew'] = array('Neues Inhaltselement oben erstellen', 'Neues Inhaltselement nach dem Inhaltselement ID %s erstellen');
/**
 * Legends
 */
$GLOBALS['TL_LANG']['tl_news_archive']['expert_legend'] = 'Experten-Einstellungen';

// vendor/contao/comments-bundle/contao/languages/de/tl_news_archive.xlf
$GLOBALS['TL_LANG']['tl_news_archive']['allowComments']['0'] = 'Kommentare aktivieren';
$GLOBALS['TL_LANG']['tl_news_archive']['allowComments']['1'] = 'Besuchern das Kommentieren von Nachrichtenbeiträgen erlauben.';
$GLOBALS['TL_LANG']['tl_news_archive']['notify']['0'] = 'Benachrichtigung an';
$GLOBALS['TL_LANG']['tl_news_archive']['notify']['1'] = 'Bitte legen Sie fest, wer beim Hinzufügen neuer Kommentare benachrichtigt wird.';
$GLOBALS['TL_LANG']['tl_news_archive']['sortOrder']['0'] = 'Sortierreihenfolge';
$GLOBALS['TL_LANG']['tl_news_archive']['sortOrder']['1'] = 'Standardmäßig werden Kommentare aufsteigend sortiert, beginnend mit dem ältesten.';
$GLOBALS['TL_LANG']['tl_news_archive']['perPage']['0'] = 'Kommentare pro Seite';
$GLOBALS['TL_LANG']['tl_news_archive']['perPage']['1'] = 'Anzahl an Kommentaren pro Seite. Geben Sie 0 ein, um den automatischen Seitenumbruch zu deaktivieren.';
$GLOBALS['TL_LANG']['tl_news_archive']['moderate']['0'] = 'Kommentare moderieren';
$GLOBALS['TL_LANG']['tl_news_archive']['moderate']['1'] = 'Kommentare erst nach Bestätigung auf der Webseite veröffentlichen.';
$GLOBALS['TL_LANG']['tl_news_archive']['bbcode']['0'] = 'BBCode erlauben';
$GLOBALS['TL_LANG']['tl_news_archive']['bbcode']['1'] = 'Besuchern das Formatieren ihrer Kommentare mittels BBCode erlauben.';
$GLOBALS['TL_LANG']['tl_news_archive']['requireLogin']['0'] = 'Login zum Kommentieren benötigt';
$GLOBALS['TL_LANG']['tl_news_archive']['requireLogin']['1'] = 'Nur angemeldeten Mitgliedern das Erstellen von Kommentaren erlauben.';
$GLOBALS['TL_LANG']['tl_news_archive']['disableCaptcha']['0'] = 'Spam-Schutz deaktivieren';
$GLOBALS['TL_LANG']['tl_news_archive']['disableCaptcha']['1'] = 'Wählen Sie diese Option nur, wenn das Erstellen von Kommentaren auf authentifizierte Benutzer beschränkt ist.';
$GLOBALS['TL_LANG']['tl_news_archive']['comments_legend'] = 'Kommentare';
$GLOBALS['TL_LANG']['tl_news_archive']['notify_admin'] = 'Systemadministrator';
$GLOBALS['TL_LANG']['tl_news_archive']['notify_author'] = 'Autor des Beitrags';
$GLOBALS['TL_LANG']['tl_news_archive']['notify_both'] = 'Autor und Systemadministrator';
$GLOBALS['TL_LANG']['tl_news_archive']['comments'] = 'Kommentare des Nachrichtenarchivs ID %s anzeigen';
