<?php

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2013 
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['title'][0] = 'Titel';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['title'][1] = 'Geben Sie dem Slide einen Namen.';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['subtitle'][0] = 'Untertitel oder Beschreibung';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['subtitle'][1] = 'Geben Sie einen Text ein.';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['published'][0] = 'Aktiv';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['published'][1] = 'Diesen Slide aktivieren.';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['transition'][0] = 'Effekt';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['transition'][1] = 'Wählen Sie den Effekt aus, mit dem dieser Slide ausgeführt werden soll. Lassen Sie das Feld leer um den Standard-Effekt des Sliders zu verwenden.';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['slideUrl'][0] = 'Link-Adresse';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['slideUrl'][1] = 'Dem Slide eine eigene Link-Adresse vergeben.';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['newWindow'][0] = 'Link in neuem Fenster öffnen';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['newWindow'][1] = 'Wählen Sie hier wenn der Link in einem Neuen Fenster bzw. Browser-Tab geöffnet werden soll.';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['slotamount'][0] = 'Anzahl der Bildunterteilungen';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['slotamount'][1] = 'Legen Sie die Anzahl der Unterteilungen fest, in die der Bildeffekt unterteilt werden soll. Individuelle Einstellungen können im Javascript Template vorgenommen werden.';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['parallax'][0] = 'Parallax-Effekt aktivieren';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['parallax'][1] = 'Aktiviert einen Parallax-Effekt für das Hintergrundbild.';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['singleSRC'][0] = 'Hauptbild';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['singleSRC'][1] = 'Wählen Sie das Hauptbild dieses Slides.';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['delay'][0] = 'Sichtbarkeit (in Sek.)';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['delay'][1] = 'Geben Sie hier die Sekunden an, die der Slide sichtbar ist.';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['masterspeed'][0] = 'Allgemeine Effektdauer';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['masterspeed'][1] = 'Geben Sie hier die allgemeine Dauer der Effekte an. Sie können die Dauer eines Effekts zusätzlich im Inhaltselement definieren.';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['lazyload'][0] = 'Hauptbild nachträglich laden';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['lazyload'][1] = 'Wählen Sie hier wenn das Hauptbild erst während der Laufzeit geladen werden soll. Das Hauptbild muss in diesem Fall die Größe des Sliders besitzen.';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['singleSRC_thumb'][0] = 'Individuelles Thumbnail für diesen Slide';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['singleSRC_thumb'][1] = 'Wählen Sie ein individuelles Vorschaubild für diesen Slide. Lassen Sie dieses Feld leer, wenn das Vorschaubild aus dem Hauptbild generiert werden soll. Vorschaubilder muss in den Slider-Einstellungen aktiviert sein.';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['background'][0] = 'Hintergrund wählen';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['background'][1] = 'Wählen Sie die Art des Hintergrunds.';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['background']['image'] = 'Bild';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['background']['colored'] = 'Farbe';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['background']['transparent'] = 'Transparent';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['background']['videomp4'] = 'HTML5 Video';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['background']['external'] = 'Externes Video (YouTube, Vimeo)';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['data_bgposition'][0] = 'Hintergrund-Ausrichtung';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['data_bgposition'][1] = 'Wählen Sie die Ausrichtung des Hintergrunds.';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['data_bgposition']['left top'] = 'Links oben (left top)';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['data_bgposition']['center top'] = 'Mitte oben (center top)';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['data_bgposition']['right top'] = 'Rechts oben (right top)';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['data_bgposition']['left center'] = 'Links zentriert (left center)';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['data_bgposition']['center center'] = 'Mittig zentriert (center center)';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['data_bgposition']['right center'] = 'Rechts zentriert (right center)';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['data_bgposition']['left bottom'] = 'Links unten (left bottom)';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['data_bgposition']['center bottom'] = 'Mitte unten (center bottom)';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['data_bgposition']['right bottom'] = 'Rechts unten (right bottom)';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['data_bgcolor'][0] = 'Hintergrundfarbe';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['data_bgcolor'][1] = 'Wählen Sie die Hintergrundfarbe.';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['data_bgrepeat'][0] = 'Hintergrund wiederholen';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['data_bgrepeat'][1] = 'Wählen Sie wenn die Hintergrundgrafik wiederholt werden soll.';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['kenburns'][0] = 'Kenburns-Effekt aktivieren';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['kenburns'][1] = 'Wählen Sie um den Kenburns-Effekt für das Hintergrundbild zu aktivieren.';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['data_bgposition_OUT'][0] = 'Hintergrund-Ausrichtung am Ende des Effekts';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['data_bgposition_OUT'][1] = 'Wählen Sie die Ausrichtung des Hintergrunds.';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['data_scale'][0] = 'Skalierung: Start / Ende';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['data_scale'][1] = 'Geben Sie die Ausgangspunkte ein.';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['data_bgfit'][0] = 'Hintergrund-Darstellung';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['data_bffit'][1] = 'Wählen Sie die Darstellungsart des Hintergrunds.';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['videoSRC'][0] = 'Quelldatei';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['videoSRC'][1] = 'Bitte wählen Sie eine MP4-Video Datei aus.';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['loop'][0] = 'Endlosschleife';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['loop'][1] = 'Das Video in einer Schleife abspielen (fügt dem <video> Element das Attribut loop hinzu)';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['nextslideatend'][0] = 'Nächsten Slide anzeigen bei Video-Ende';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['nextslideatend'][1] = 'Den nächsten Slide automatisch anzeigen wenn das Video beendet ist.';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['autoplay'][0] = 'Autoplay';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['autoplay'][1] = 'Das Video automatisch starten.';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['controls'][0] = 'Bedienelemente hinzufügen';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['controls'][1] = 'Dem Video die Browser/HTML5 Bedienleiste hinzufügen (fügt dem <video> Element das Attribut controls hinzu)';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['singleSRC_video'][0] = 'Vorschaubild';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['singleSRC_video'][1] = 'Bitte wählen Sie dasVorschaubild für das Video.';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['videoURL'][0] = 'Video URL';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['videoURL'][1] = 'Geben Sie die URL zum Video an. YouTube Videos müssen über den "einbetten"-Link eingefügt werden z.b. http://www.youtube.com/embed/QeMbgvqtIqg.</br>Zusätzliche Parameter können über GET Parameter ergänzt werden. z.B. ?rel=0, wenn bei Youtube Video keine verwandten Videos am Ende angezeigt werden sollen. Siehe: https://developers.google.com/youtube/player_parameters?hl=de';
/**
 * Legends
 */
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['title_legend'] = 'Titel und Effekt';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['expert_legend'] = 'Experten-Einstellungen';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['settings_legend'] = 'Slide-Einstellungen';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['expert_settings_legend'] = 'Zusätzliche Einstellungen';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['thumbnail_legend'] = 'Vorschaubilder-Einstellungen';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['template_legend'] = 'Template-Einstellungen';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['navigation_legend'] = 'Steuerungs-Einstellungen';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['background_legend'] = 'Hintergrund-Einstellungen';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['video_source_legend'] = 'Video-Quelle';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['video_settings_legend'] = 'Video-Einstellungen';
/**
 * Buttons
 */
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['new'] = array('Neues Slide-Element', 'Ein neues Slide-Element erstellen');
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['edit'][0] = 'Slide bearbeiten';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['edit'][1] = 'Inhalte des Slides ID %s bearbeiten';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['editheader'][0] = 'Slide bearbeiten';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['editheader'][1] = 'Einstellungen des Slides ID %s bearbeiten';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['copy'][0] = 'Slide kopieren';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['copy'][1] = 'Slide ID %s kopieren';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['delete'][0] = 'Slide entfernen';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['delete'][1] = 'Slide ID %s entfernen';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['show'][0] = 'Details';
$GLOBALS['TL_LANG']['tl_revolutionslider_slides']['show'][1] = 'Details des Slides ID %s anzeigen';
