<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2024
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

 $GLOBALS['TL_LANG']['tl_maintenance']['pct_themeupdater']['jobs'] = 'Theme Updater Tasks';
 $GLOBALS['TL_LANG']['tl_maintenance']['pct_themeupdater']['run_job'] = 'Start';
 $GLOBALS['TL_LANG']['tl_maintenance']['pct_themeupdater']['jobs_done'] = 'Task(s) [%s] executed';
 
 /**
  * Jobs
  */
 $GLOBALS['TL_LANG']['tl_maintenance']['pct_themeupdater']['news_order'][0] = 'News List Sorting';
 $GLOBALS['TL_LANG']['tl_maintenance']['pct_themeupdater']['news_order'][1] = 'Change news list sorting "date DESC" (Unknown Option) to "order_date_desc"';
 $GLOBALS['TL_LANG']['tl_maintenance']['pct_themeupdater']['center_center_to_crop'][0] = 'Update Image Size Selections';
 $GLOBALS['TL_LANG']['tl_maintenance']['pct_themeupdater']['center_center_to_crop'][1] = 'Change image size setting "CENTER_CENTER" (Unknown Option) to "CROP"';
 $GLOBALS['TL_LANG']['tl_maintenance']['pct_themeupdater']['form_textfield_form_text'][0] = 'Form Field Template Selections';
 $GLOBALS['TL_LANG']['tl_maintenance']['pct_themeupdater']['form_textfield_form_text'][1] = 'Update text form field template selections from form_textfield to form_text'; 