<?php

namespace ContainerXbKdRgj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContao_Fragment_Contao_FrontendModule_TwoFactorService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'contao.fragment._contao.frontend_module.two_factor' shared service.
     *
     * @return \Contao\CoreBundle\Controller\FrontendModule\TwoFactorController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Fragment/FragmentOptionsAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Controller/AbstractFragmentController.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Controller/FrontendModule/AbstractFrontendModuleController.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Controller/FrontendModule/TwoFactorController.php';

        $container->services['contao.fragment._contao.frontend_module.two_factor'] = $instance = new \Contao\CoreBundle\Controller\FrontendModule\TwoFactorController();

        $a = $container->load('get_ServiceLocator_VH1AYW0_Contao_Fragment_Contao_FrontendModule_TwoFactorService');

        $instance->setContainer($a);
        $instance->setFragmentOptions(['type' => 'two_factor', 'category' => 'user', 'template' => 'mod_two_factor', 'method' => NULL, 'renderer' => NULL, 'priority' => 0, 'debugController' => 'Contao\\CoreBundle\\Controller\\FrontendModule\\TwoFactorController']);
        $instance->setContainer($a);

        return $instance;
    }
}
