<?php

namespace ContainerXbKdRgj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContao_Listener_DataContainer_ContentCompositionService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'contao.listener.data_container.content_composition' shared service.
     *
     * @return \Contao\CoreBundle\EventListener\DataContainer\ContentCompositionListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/EventListener/DataContainer/ContentCompositionListener.php';

        return $container->services['contao.listener.data_container.content_composition'] = new \Contao\CoreBundle\EventListener\DataContainer\ContentCompositionListener(($container->services['contao.framework'] ?? self::getContao_FrameworkService($container)), ($container->services['security.helper'] ?? self::getSecurity_HelperService($container)), ($container->services['contao.routing.page_registry'] ?? self::getContao_Routing_PageRegistryService($container)), ($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
