<?php

namespace ContainerXbKdRgj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContaoNewsletter_Listener_NewsletterRecipientsEditButtonsService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'contao_newsletter.listener.newsletter_recipients_edit_buttons' shared service.
     *
     * @return \Contao\NewsletterBundle\EventListener\NewsletterRecipientsEditButtonsListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao/newsletter-bundle/src/EventListener/NewsletterRecipientsEditButtonsListener.php';

        return $container->services['contao_newsletter.listener.newsletter_recipients_edit_buttons'] = new \Contao\NewsletterBundle\EventListener\NewsletterRecipientsEditButtonsListener();
    }
}
