<?php

namespace ContainerXbKdRgj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContao_Fragment_Contao_ContentElement_HtmlService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'contao.fragment._contao.content_element.html' shared service.
     *
     * @return \Contao\CoreBundle\Controller\ContentElement\HtmlController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Fragment/FragmentOptionsAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Controller/AbstractFragmentController.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Controller/ContentElement/AbstractContentElementController.php';
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Controller/ContentElement/HtmlController.php';

        $container->services['contao.fragment._contao.content_element.html'] = $instance = new \Contao\CoreBundle\Controller\ContentElement\HtmlController();

        $a = $container->load('get_ServiceLocator_GSfX_Ym_Contao_Fragment_Contao_ContentElement_HtmlService');

        $instance->setContainer($a);
        $instance->setFragmentOptions(['type' => 'html', 'category' => 'texts', 'template' => 'content_element/html', 'method' => NULL, 'renderer' => NULL, 'nestedFragments' => false, 'priority' => 0, 'debugController' => 'Contao\\CoreBundle\\Controller\\ContentElement\\HtmlController']);
        $instance->setContainer($a);

        return $instance;
    }
}
