<?php

namespace ContainerXbKdRgj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDcaRelationsListenerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the private 'Codefog\HasteBundle\EventListener\DcaRelationsListener' shared autowired service.
     *
     * @return \Codefog\HasteBundle\EventListener\DcaRelationsListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/codefog/contao-haste/src/EventListener/DcaRelationsListener.php';

        $a = ($container->services['Codefog\\HasteBundle\\DcaRelationsManager'] ?? $container->load('getDcaRelationsManagerService'));

        if (isset($container->privates['Codefog\\HasteBundle\\EventListener\\DcaRelationsListener'])) {
            return $container->privates['Codefog\\HasteBundle\\EventListener\\DcaRelationsListener'];
        }

        return $container->privates['Codefog\\HasteBundle\\EventListener\\DcaRelationsListener'] = new \Codefog\HasteBundle\EventListener\DcaRelationsListener($a);
    }
}
