<?php

namespace ContainerXbKdRgj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSitemapControllerService extends Contao_ManagerBundle_HttpKernel_ContaoKernelProdContainer
{
    /*
     * Gets the public 'Contao\CoreBundle\Controller\SitemapController' shared service.
     *
     * @return \Contao\CoreBundle\Controller\SitemapController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/contao/core-bundle/src/Controller/SitemapController.php';

        $container->services['Contao\\CoreBundle\\Controller\\SitemapController'] = $instance = new \Contao\CoreBundle\Controller\SitemapController(($container->services['contao.routing.page_registry'] ?? self::getContao_Routing_PageRegistryService($container)), ($container->services['contao.routing.page_finder'] ?? self::getContao_Routing_PageFinderService($container)), ($container->services['contao.routing.content_url_generator'] ?? self::getContao_Routing_ContentUrlGeneratorService($container)));

        $instance->setContainer(($container->privates['.service_locator.8pXkOyT'] ?? self::get_ServiceLocator_8pXkOyTService($container))->withContext('Contao\\CoreBundle\\Controller\\SitemapController', $container));

        return $instance;
    }
}
