<?php
/**
 * Contao
 * German translation file
 *
 * copyright  Tim Gatzky 2019
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:
 *
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

// New grid button
$GLOBALS['TL_LANG']['MSC']['new_grid'] 						= array('Grid mit fixen Spalten','Eine neue Grid-Vorlage auswählen und einfügen.');
$GLOBALS['TL_LANG']['MSC']['new_flex'] 						= array('Neues Grid','Eine neue Grid-Reihe anlegen');
$GLOBALS['TL_LANG']['MSC']['new_flex']['cols_1']				= '1 Spalte';
$GLOBALS['TL_LANG']['MSC']['new_flex']['cols_2']				= '2 Spalten';
$GLOBALS['TL_LANG']['MSC']['new_flex']['cols_3']				= '3 Spalten';
$GLOBALS['TL_LANG']['MSC']['new_flex']['cols_4']				= '4 Spalten';
//
$GLOBALS['TL_LANG']['autogrid_css']['full'] 				= 'Volle Breite (full)';
$GLOBALS['TL_LANG']['autogrid_css']['one_half'] 			= '1/2 (one_half)';
$GLOBALS['TL_LANG']['autogrid_css']['one_third'] 			= '1/3 (one_third)';
$GLOBALS['TL_LANG']['autogrid_css']['two_third'] 			= '2/3 (two_third)';
$GLOBALS['TL_LANG']['autogrid_css']['one_fourth']			= '1/4 (one_fourth)';
$GLOBALS['TL_LANG']['autogrid_css']['two_fourth']			= '2/4 (two_fourth)';
$GLOBALS['TL_LANG']['autogrid_css']['three_fourth']			= '3/4 (three_fourth)';
$GLOBALS['TL_LANG']['autogrid_css']['one_fifth'] 			= '1/5 (one_fifth)';
$GLOBALS['TL_LANG']['autogrid_css']['two_fifth'] 			= '2/5 (two_fifth)';
$GLOBALS['TL_LANG']['autogrid_css']['three_fifth'] 			= '3/5 (three_fifth)';
$GLOBALS['TL_LANG']['autogrid_css']['four_fifth'] 			= '4/5 (four_fifth)';
$GLOBALS['TL_LANG']['autogrid_css']['one_sixth'] 			= '1/6 (one_sixth)';
$GLOBALS['TL_LANG']['autogrid_css']['two_sixth'] 			= '2/6 (two_sixth)';
$GLOBALS['TL_LANG']['autogrid_css']['three_sixth'] 			= '3/6 (three_sixth)';
$GLOBALS['TL_LANG']['autogrid_css']['four_sixth'] 			= '4/6 (four_sixth)';
$GLOBALS['TL_LANG']['autogrid_css']['five_sixth'] 			= '5/6 (five_sixth)';
// mobile
$GLOBALS['TL_LANG']['autogrid_css']['full'] 				= 'Volle Breite (full)';
$GLOBALS['TL_LANG']['autogrid_css']['one_half_m'] 			= '1/2 (one_half)';
$GLOBALS['TL_LANG']['autogrid_css']['one_third_m'] 			= '1/3 (one_third)';
$GLOBALS['TL_LANG']['autogrid_css']['two_third_m'] 			= '2/3 (two_third)';
$GLOBALS['TL_LANG']['autogrid_css']['one_fourth_m']			= '1/4 (one_fourth)';
$GLOBALS['TL_LANG']['autogrid_css']['two_fourth_m']			= '2/4 (two_fourth)';
$GLOBALS['TL_LANG']['autogrid_css']['three_fourth_m']		= '3/4 (three_fourth)';
$GLOBALS['TL_LANG']['autogrid_css']['one_fifth_m'] 			= '1/5 (one_fifth)';
$GLOBALS['TL_LANG']['autogrid_css']['two_fifth_m'] 			= '2/5 (two_fifth)';
$GLOBALS['TL_LANG']['autogrid_css']['three_fifth_m'] 		= '3/5 (three_fifth)';
$GLOBALS['TL_LANG']['autogrid_css']['four_fifth_m'] 		= '4/5 (four_fifth)';
$GLOBALS['TL_LANG']['autogrid_css']['one_sixth_m'] 			= '1/6 (one_sixth)';
$GLOBALS['TL_LANG']['autogrid_css']['two_sixth_m'] 			= '2/6 (two_sixth)';
$GLOBALS['TL_LANG']['autogrid_css']['three_sixth_m'] 		= '3/6 (three_sixth)';
$GLOBALS['TL_LANG']['autogrid_css']['four_sixth_m'] 		= '4/6 (four_sixth)';
$GLOBALS['TL_LANG']['autogrid_css']['five_sixth_m'] 		= '5/6 (five_sixth)';
// offsets
$GLOBALS['TL_LANG']['autogrid_offset']['offset_one_half'] 			= '1/2 (one_half)';
$GLOBALS['TL_LANG']['autogrid_offset']['offset_one_third'] 			= '1/3 (one_third)';
$GLOBALS['TL_LANG']['autogrid_offset']['offset_two_third'] 			= '2/3 (two_third)';
$GLOBALS['TL_LANG']['autogrid_offset']['offset_one_fourth']			= '1/4 (one_fourth)';
$GLOBALS['TL_LANG']['autogrid_offset']['offset_two_fourth']			= '2/4 (two_fourth)';
$GLOBALS['TL_LANG']['autogrid_offset']['offset_three_fourth']		= '3/4 (three_fourth)';
$GLOBALS['TL_LANG']['autogrid_offset']['offset_one_fifth'] 			= '1/5 (one_fifth)';
$GLOBALS['TL_LANG']['autogrid_offset']['offset_two_fifth'] 			= '2/5 (two_fifth)';
$GLOBALS['TL_LANG']['autogrid_offset']['offset_three_fifth'] 		= '3/5 (three_fifth)';
$GLOBALS['TL_LANG']['autogrid_offset']['offset_four_fifth'] 		= '4/5 (four_fifth)';
$GLOBALS['TL_LANG']['autogrid_offset']['offset_one_sixth'] 			= '1/6 (one_sixth)';
$GLOBALS['TL_LANG']['autogrid_offset']['offset_two_sixth'] 			= '2/6 (two_sixth)';
$GLOBALS['TL_LANG']['autogrid_offset']['offset_three_sixth'] 		= '3/6 (three_sixth)';
$GLOBALS['TL_LANG']['autogrid_offset']['offset_four_sixth'] 		= '4/6 (four_sixth)';
$GLOBALS['TL_LANG']['autogrid_offset']['offset_five_sixth'] 		= '5/6 (five_sixth)';
// align
$GLOBALS['TL_LANG']['autogrid_align']['align_left_top'] 		= 'Links | Oben';
$GLOBALS['TL_LANG']['autogrid_align']['align_left_center'] 		= 'Links | Mittig';
$GLOBALS['TL_LANG']['autogrid_align']['align_left_bottom'] 		= 'Links | Unten';
$GLOBALS['TL_LANG']['autogrid_align']['align_center_top'] 		= 'Mittig | Oben';
$GLOBALS['TL_LANG']['autogrid_align']['align_center_center'] 	= 'Mittig | Mittig';
$GLOBALS['TL_LANG']['autogrid_align']['align_center_bottom'] 	= 'Mittig | Unten';
$GLOBALS['TL_LANG']['autogrid_align']['align_right_top'] 		= 'Rechts | Oben';
$GLOBALS['TL_LANG']['autogrid_align']['align_right_center'] 	= 'Rechts | Mittig';
$GLOBALS['TL_LANG']['autogrid_align']['align_right_bottom'] 	= 'Rechts | Unten';
$GLOBALS['TL_LANG']['autogrid_align']['align_left'] 			= 'Links';
$GLOBALS['TL_LANG']['autogrid_align']['align_center'] 			= 'Mittig';
$GLOBALS['TL_LANG']['autogrid_align']['align_right'] 			= 'Rechts';
// gutter
$GLOBALS['TL_LANG']['autogrid_gutter']['gutter_none'] 			= 'Kein Abstand';
$GLOBALS['TL_LANG']['autogrid_gutter']['gutter_s'] 				= 'Klein';
$GLOBALS['TL_LANG']['autogrid_gutter']['gutter_m'] 				= 'Mittel';
$GLOBALS['TL_LANG']['autogrid_gutter']['gutter_l'] 				= 'Groß';
//-- clockwise col classes
$GLOBALS['TL_LANG']['autogrid_css']['col_12'] 				= 'col_12 (100%)';
$GLOBALS['TL_LANG']['autogrid_css']['col_11'] 				= 'col_11';
$GLOBALS['TL_LANG']['autogrid_css']['col_10'] 				= 'col_10';
$GLOBALS['TL_LANG']['autogrid_css']['col_9'] 				= 'col_9 (75%)';
$GLOBALS['TL_LANG']['autogrid_css']['col_8'] 				= 'col_8 (66%)';
$GLOBALS['TL_LANG']['autogrid_css']['col_7'] 				= 'col_7';
$GLOBALS['TL_LANG']['autogrid_css']['col_6'] 				= 'col_6 (50%)';
$GLOBALS['TL_LANG']['autogrid_css']['col_5'] 				= 'col_5';
$GLOBALS['TL_LANG']['autogrid_css']['col_4'] 				= 'col_4 (33%)';
$GLOBALS['TL_LANG']['autogrid_css']['col_3'] 				= 'col_3 (25%)';
$GLOBALS['TL_LANG']['autogrid_css']['col_2'] 				= 'col_2';
$GLOBALS['TL_LANG']['autogrid_css']['col_1'] 				= 'col_1';
// tablet
$GLOBALS['TL_LANG']['autogrid_css']['col_12_t'] 			= 'col_12 (100%)';
$GLOBALS['TL_LANG']['autogrid_css']['col_11_t'] 			= 'col_11';
$GLOBALS['TL_LANG']['autogrid_css']['col_10_t'] 			= 'col_10';
$GLOBALS['TL_LANG']['autogrid_css']['col_9_t'] 				= 'col_9 (75%)';
$GLOBALS['TL_LANG']['autogrid_css']['col_8_t'] 				= 'col_8 (66%)';
$GLOBALS['TL_LANG']['autogrid_css']['col_7_t'] 				= 'col_7';
$GLOBALS['TL_LANG']['autogrid_css']['col_6_t'] 				= 'col_6 (50%)';
$GLOBALS['TL_LANG']['autogrid_css']['col_5_t'] 				= 'col_5';
$GLOBALS['TL_LANG']['autogrid_css']['col_4_t'] 				= 'col_4 (33%)';
$GLOBALS['TL_LANG']['autogrid_css']['col_3_t'] 				= 'col_3 (25%)';
$GLOBALS['TL_LANG']['autogrid_css']['col_2_t'] 				= 'col_2';
$GLOBALS['TL_LANG']['autogrid_css']['col_1_t'] 				= 'col_1';
// mobile
$GLOBALS['TL_LANG']['autogrid_css']['col_12_m'] 			= 'col_12 (100%)';
$GLOBALS['TL_LANG']['autogrid_css']['col_11_m'] 			= 'col_11';
$GLOBALS['TL_LANG']['autogrid_css']['col_10_m'] 			= 'col_10';
$GLOBALS['TL_LANG']['autogrid_css']['col_9_m'] 				= 'col_9 (75%)';
$GLOBALS['TL_LANG']['autogrid_css']['col_8_m'] 				= 'col_8 (66%)';
$GLOBALS['TL_LANG']['autogrid_css']['col_7_m'] 				= 'col_7';
$GLOBALS['TL_LANG']['autogrid_css']['col_6_m'] 				= 'col_6 (50%)';
$GLOBALS['TL_LANG']['autogrid_css']['col_5_m'] 				= 'col_5';
$GLOBALS['TL_LANG']['autogrid_css']['col_4_m'] 				= 'col_4 (33%)';
$GLOBALS['TL_LANG']['autogrid_css']['col_3_m'] 				= 'col_3 (25%)';
$GLOBALS['TL_LANG']['autogrid_css']['col_2_m'] 				= 'col_2';
$GLOBALS['TL_LANG']['autogrid_css']['col_1_m'] 				= 'col_1';
// offsets
$GLOBALS['TL_LANG']['autogrid_offset']['offset_col_12'] 	= 'col_12 (100%)';
$GLOBALS['TL_LANG']['autogrid_offset']['offset_col_11'] 	= 'col_11';
$GLOBALS['TL_LANG']['autogrid_offset']['offset_col_10'] 	= 'col_10';
$GLOBALS['TL_LANG']['autogrid_offset']['offset_col_9']  	= 'col_9 (75%)';
$GLOBALS['TL_LANG']['autogrid_offset']['offset_col_8']  	= 'col_8 (66%)';
$GLOBALS['TL_LANG']['autogrid_offset']['offset_col_7']  	= 'col_7';
$GLOBALS['TL_LANG']['autogrid_offset']['offset_col_6']  	= 'col_6 (50%)';
$GLOBALS['TL_LANG']['autogrid_offset']['offset_col_5']  	= 'col_5';
$GLOBALS['TL_LANG']['autogrid_offset']['offset_col_4']  	= 'col_4 (33%)';
$GLOBALS['TL_LANG']['autogrid_offset']['offset_col_3']  	= 'col_3 (25%)';
$GLOBALS['TL_LANG']['autogrid_offset']['offset_col_2']  	= 'col_2';
$GLOBALS['TL_LANG']['autogrid_offset']['offset_col_1']  	= 'col_1';
// sameheight
$GLOBALS['TL_LANG']['autogrid_sameheight']['0']  			= 'Nein';
$GLOBALS['TL_LANG']['autogrid_sameheight']['1']  			= 'Ja';
// no_gutter
$GLOBALS['TL_LANG']['autogrid_no_gutter']['0']  			= 'Nein';
$GLOBALS['TL_LANG']['autogrid_no_gutter']['1']  			= 'Ja';
// grid preset references
$GLOBALS['TL_LANG']['autogrid_grid']['20_20_20_20_20']		= '20 20 20 20 20';
$GLOBALS['TL_LANG']['autogrid_grid']['25_25_25_25']			= '25 25 25 25';
$GLOBALS['TL_LANG']['autogrid_grid']['33_33_33']			= '33 33 33';
$GLOBALS['TL_LANG']['autogrid_grid']['50_25_25']			= '50 25 25';
$GLOBALS['TL_LANG']['autogrid_grid']['25_50_25']			= '25 50 25';
$GLOBALS['TL_LANG']['autogrid_grid']['25_25_50']			= '25 25 50';
$GLOBALS['TL_LANG']['autogrid_grid']['40_30_30']			= '40 30 30';
$GLOBALS['TL_LANG']['autogrid_grid']['30_40_30']			= '30 40 30';
$GLOBALS['TL_LANG']['autogrid_grid']['30_30_40']			= '30 30 40';
$GLOBALS['TL_LANG']['autogrid_grid']['20_40_40']			= '20 40 40';
$GLOBALS['TL_LANG']['autogrid_grid']['40_20_40']			= '40 20 40';
$GLOBALS['TL_LANG']['autogrid_grid']['40_40_20']			= '40 40 20';
$GLOBALS['TL_LANG']['autogrid_grid']['50_50']				= '50 50';
$GLOBALS['TL_LANG']['autogrid_grid']['85_15']				= '85 15';
$GLOBALS['TL_LANG']['autogrid_grid']['15_85']				= '15 85';
$GLOBALS['TL_LANG']['autogrid_grid']['80_20']				= '80 20';
$GLOBALS['TL_LANG']['autogrid_grid']['20_80']				= '20 80';
$GLOBALS['TL_LANG']['autogrid_grid']['75_25']				= '75 25';
$GLOBALS['TL_LANG']['autogrid_grid']['25_75']				= '25 75';
$GLOBALS['TL_LANG']['autogrid_grid']['70_30']				= '70 30';
$GLOBALS['TL_LANG']['autogrid_grid']['30_70']				= '30 70';
$GLOBALS['TL_LANG']['autogrid_grid']['66_33']				= '66 33';
$GLOBALS['TL_LANG']['autogrid_grid']['33_66']				= '33 66';
$GLOBALS['TL_LANG']['autogrid_grid']['60_40']				= '60 40';
$GLOBALS['TL_LANG']['autogrid_grid']['40_60']				= '40 60';
$GLOBALS['TL_LANG']['autogrid_grid']['100']					= '100';
// messages
$GLOBALS['TL_LANG']['AUTOGRID_MESSAGES']['gridInfo']		= 'Grid mit fixen Spalten: %s';
$GLOBALS['TL_LANG']['AUTOGRID_MESSAGES']['gridInfo_customSettings']	= 'Abweichende Grid-Einstellungen: %s (Standard: %s).';
$GLOBALS['TL_LANG']['AUTOGRID_MESSAGES']['flexInfo']		= 'AutoGrid wurde aktiviert f&uuml;r Element innerhalb einer AutoGrid-Reihe.';
$GLOBALS['TL_LANG']['AUTOGRID_MESSAGES']['colInfo']			= 'AutoGrid wurde deaktiviert f&uuml;r Element innerhalb einer AutoGrid-Spalte.';
// Grid Presets backend page
$GLOBALS['TL_LANG']['page_grid_preset']['counter']			= 'Anzahl: %s';
$GLOBALS['TL_LANG']['page_grid_preset']['categories']		= array('Kategorien','Wählen Sie eine Kategorie');
$GLOBALS['TL_LANG']['page_grid_preset']['categories']['1cols'] = '1-spaltig';
$GLOBALS['TL_LANG']['page_grid_preset']['categories']['2cols'] = '2-spaltig';
$GLOBALS['TL_LANG']['page_grid_preset']['categories']['3cols'] = '3-spaltig';
$GLOBALS['TL_LANG']['page_grid_preset']['categories']['4cols'] = '4-spaltig';
$GLOBALS['TL_LANG']['page_grid_preset']['categories']['5cols'] = '5-spaltig';
// Wildcard
$GLOBALS['TL_LANG']['autogrid_wildcard']['sameheight']['label'] = 'Gleiche Höhe';
$GLOBALS['TL_LANG']['autogrid_wildcard']['gutter']['label'] = 'Spaltenabstände:';
$GLOBALS['TL_LANG']['autogrid_wildcard']['gutter']['gutter_l'] = 'Abstand: L';
$GLOBALS['TL_LANG']['autogrid_wildcard']['gutter']['gutter_m'] = 'Abstand: M';
$GLOBALS['TL_LANG']['autogrid_wildcard']['gutter']['gutter_s'] = 'Abstand: S';
$GLOBALS['TL_LANG']['autogrid_wildcard']['gutter']['gutter_none'] = 'Kein Abstand';
// Viewport panel
$GLOBALS['TL_LANG']['autogrid_viewport_panel']['desktop'] = 'Desktop';
$GLOBALS['TL_LANG']['autogrid_viewport_panel']['tablet'] = 'Tablet';
$GLOBALS['TL_LANG']['autogrid_viewport_panel']['mobile'] = 'Mobile';

/**
 * Error messages
 */
$GLOBALS['TL_LANG']['XPT']['grid_rgxp']['column_count']			= 'Anzahl der Spalten ist abweichend. %s von %s';
$GLOBALS['TL_LANG']['XPT']['grid_rgxp']['wrong_or_missing_unit'] = 'Bitte geben Sie nur % Zeichen als Einheit ein.';
$GLOBALS['TL_LANG']['XPT']['grid_rgxp']['no_numeric_value'] 	= 'Fehlender Zahlenwert an %s. Stelle';
$GLOBALS['TL_LANG']['XPT']['grid_rgxp']['invalid_value'] 		= 'Zahlenwerte erwartet an %s. Stelle';
$GLOBALS['TL_LANG']['XPT']['grid_rgxp']['higher_than_zero'] 	= 'Erwarteter Zahlenwert an %s. Stelle ist kleiner oder gleich Null (0).';

/**
 * Misc 
 */
$GLOBALS['TL_LANG']['MSC']['deleteBlock'] = array('Gesamten Blocks %s inklusive Inhalten löschen','Gesamten Block %s inklusive Inhalten löschen');
$GLOBALS['TL_LANG']['MSC']['deleteBlockConfirm'] = 'Gesamten Block inklusive Inhalt löschen?';
