<?php

// vendor/contao/core-bundle/contao/languages/en/exception.xlf
$GLOBALS['TL_LANG']['XPT']['error'] = 'An error occurred';
$GLOBALS['TL_LANG']['XPT']['matter'] = 'What\'s the matter?';
$GLOBALS['TL_LANG']['XPT']['howToFix'] = 'How can I fix the issue?';
$GLOBALS['TL_LANG']['XPT']['more'] = 'Tell me more, please';
$GLOBALS['TL_LANG']['XPT']['hint'] = 'To customize this notice, create a custom Twig template overriding <em>%s</em>.';
$GLOBALS['TL_LANG']['XPT']['errorOccurred'] = 'An error occurred while executing this script. Something does not work properly.';
$GLOBALS['TL_LANG']['XPT']['errorFixOne'] = 'Open the current log file in the <code>var/logs</code> directory and find the associated error message (usually the last one).';
$GLOBALS['TL_LANG']['XPT']['errorExplain'] = 'The script execution stopped, because something does not work properly. The actual error message is hidden by this notice for security reasons and can be found in the current log file (see above). If you do not understand the error message or do not know how to fix the problem, visit the <a href="%s" target="_blank" rel="noreferrer noopener">Contao support page</a>.';
$GLOBALS['TL_LANG']['XPT']['requestToken'] = 'Invalid request token';
$GLOBALS['TL_LANG']['XPT']['invalidToken'] = 'The request token could not be verified.';
$GLOBALS['TL_LANG']['XPT']['tokenRetry'] = 'Please <a href="javascript:window.location.href=window.location.href">click here</a> and try again. Do not use the back button of your browser.';
$GLOBALS['TL_LANG']['XPT']['tokenExplainOne'] = 'This error occurs if there is a POST request without a valid authentication token. In Contao 2.10, the referer check has been replaced with a request token system. If the problem persists, you may be using an incompatible third-party extension or have not correctly updated your Contao installation.';
$GLOBALS['TL_LANG']['XPT']['tokenExplainTwo'] = 'For more information, visit the <a href="%s" target="_blank" rel="noreferrer noopener">Contao support page</a>.';
$GLOBALS['TL_LANG']['XPT']['unavailable'] = 'Service unavailable';
$GLOBALS['TL_LANG']['XPT']['maintenance'] = 'The website is currently not available. Please come back later.';
$GLOBALS['TL_LANG']['XPT']['missingRouteParameters']['title'] = 'Unable to generate front end URL';
$GLOBALS['TL_LANG']['XPT']['missingRouteParameters']['matter'] = 'The URL could not be generated, because the route has mandatory parameters that are not given. Additional information (e.g. a news alias) must be provided.';
$GLOBALS['TL_LANG']['XPT']['missingRouteParameters']['explain'] = 'Symfony routes can have variable parameters, which are validated using regular expressions. The following configuration could not be resolved:';
$GLOBALS['TL_LANG']['XPT']['missingRouteParameters']['path'] = 'Route path';
$GLOBALS['TL_LANG']['XPT']['missingRouteParameters']['parameterName'] = 'Name';
$GLOBALS['TL_LANG']['XPT']['missingRouteParameters']['parameterRequirement'] = 'Requirement (Regex)';
$GLOBALS['TL_LANG']['XPT']['missingRouteParameters']['parameterDefault'] = 'Default value';
$GLOBALS['TL_LANG']['XPT']['missingRouteParameters']['parameterEmpty'] = 'empty';

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2018
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
/**
 * Errors
 */
$GLOBALS['TL_LANG']['XPT']['pct_theme_updater']['unzip_error'] = 'Unzipping the file %s failed.';
$GLOBALS['TL_LANG']['XPT']['pct_theme_updater']['zip_content_error'] = 'Required contents (%s) not found in the unzipped directory.';
$GLOBALS['TL_LANG']['XPT']['pct_theme_updater']['sql_not_found'] = 'SQL installation template not found.';
$GLOBALS['TL_LANG']['XPT']['pct_theme_updater']['session_lost'] = 'The license session has expired. Please restart the installation.';
$GLOBALS['TL_LANG']['XPT']['pct_theme_updater']['version_conflict'] = 'Please use Contao LTS versions: 4.13 or 5.3.';
$GLOBALS['TL_LANG']['XPT']['pct_theme_updater']['memory_limit'] = 'Memory limit (memory_limit) too low (%s). Min.: 512M';
$GLOBALS['TL_LANG']['XPT']['pct_theme_updater']['changelog_not_found'] = 'Current theme version could not be determined. (/templates/changelog.txt not found)';
$GLOBALS['TL_LANG']['XPT']['pct_theme_updater']['client_version_conflict'] = 'A new version of the Theme Updater is available. Please update the module.';
$GLOBALS['TL_LANG']['XPT']['pct_theme_updater']['theme_compatibility_conflict'] = 'Your current theme version %s is not compatible with Contao %s. Please update the theme from Contao %s and then update Contao.';
$GLOBALS['TL_LANG']['XPT']['pct_theme_updater']['theme_version_conflict'] = 'Contao %s is not supported. Supported Contao versions: %s';
$GLOBALS['TL_LANG']['XPT']['pct_theme_updater']['min_theme_version'] = 'The recommended starting version for the update is EclipseX 4.0.';

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2016
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
/**
 * Errors
 */
$GLOBALS['TL_LANG']['XPT']['pct_themer']['no_active_pages_found'] = 'No active pages found.';
$GLOBALS['TL_LANG']['XPT']['pct_themer']['no_export_data'] = 'No Export-data found in session. Please run the export routine again.';
$GLOBALS['TL_LANG']['XPT']['pct_themer']['import_already_done'] = 'Import completed. Clear the user session to run the import again.';
$GLOBALS['TL_LANG']['XPT']['pct_themer']['no_theme_record_selected'] = 'Please choose the theme record as target for the module records.';
$GLOBALS['TL_LANG']['XPT']['pct_themer']['pages_with_no_layout_save'] = 'Root pages without Theme-Designer save states found.';

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2014
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
$GLOBALS['TL_LANG']['PCT_CUSTOMCATALOG']['XPT']['emptyDataContainerArray'] = 'The DataContainer array for table %s is empty. The script has been stopped. Please check your return values.';
$GLOBALS['TL_LANG']['PCT_CUSTOMCATALOG']['XPT']['customelements_version_too_low'] = 'Your current CustomCatalog version (%s) requires CustomElements version (%s). Current version is (%s). Please update CustomElements. CustomCatalog has been stopped from processing.';
$GLOBALS['TL_LANG']['PCT_CUSTOMCATALOG']['XPT']['reservedSqlWord'] = '"%s" is a reserved term. Please use a different term';
