<?php

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2018 
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
/**
 * Errors
 */
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['label_key'] = 'License Key / Order Number';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['label_email'] = 'Order Email Address';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['submit_license'] = 'Query License';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['submit_install'] = 'Start Update';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['sql_template_info'] = 'SQL Template File: %s';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['input_email'][0] = 'Order Email Address';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['input_email'][1] = 'Please enter the email address of your customer account.';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['input_license'][0] = 'License Key / Order Number (Theme Updater)';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['input_license'][1] = 'You can find the order number on your invoice or in your customer account.';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['input_license_theme'][0] = 'Order Number (EclipseX or EclipseX + CustomCatalog Bundle)';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['input_license_theme'][1] = 'You can find the order number on your invoice or in your customer account.';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['label_status'] = 'Status: %s';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['label_step'] = 'Step: %s';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['button_reset'][0] = 'Reset';
// link text
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['button_reset'][1] = 'Resets the theme license information and restarts the update process.';
// title
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['domainRegistrationError'] = '
The domain of the theme license holder stored in the customer area differs from the domain <span style="font-weight:bold">%s</span>.<br><br>Please update your license holder domain (order number <span style="font-weight:bold">%s</span>) in your <a href="https://login.premium-contao-themes.com/" target="_blank" style="text-decoration:underline;">customer area</a>.<br>
You can find the license terms and answers to frequently asked questions (FAQ) <a href="https://www.premium-contao-themes.com/lizenzbestimmungen.html" target="_blank" style="text-decoration:underline;">here</a>.<br><br>
When starting the update routine, the request from the domain (%s) is saved in our system.<br><br>Note: For updates on a subdomain, the subdomain "update."LICENSEE_DOMAIN is available.';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['sql_template_headline'] = 'Ready to import the demo website.';
// title
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['sql_template_subheadline'] = 'Note: Existing data will be lost. Your user profile will remain intact.';
// title
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['sql_template_info'] = 'The import of the demo website (SQL template) ';
// title
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['button_sql_template_import'] = 'Execute import';
// title
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['choose_product_info'] = 'Please select the product to be installed.';
// title
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['product_select_blankOption'] = 'Select product...';
// title
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['button_systemlog'][0] = 'Go to System Log...';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['welcome_info'] = 'Enter your order number and order email address of your EclipseX / EclipseX + CustomCatalog order and click "Check License". After your license information is verified, you will be redirected.';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['sql_template_import_info'] = 'The SQL import may take a few minutes. After a successful import, you will be redirected to the Contao login.';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['access_denied'] = 'Message: %s';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['errors'] = 'Error: %s';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['not_supported'] = 'The updater supports the following products: %s';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['button_installer_buy'] = 'Contao Installer';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['enter_updater_license_info'] = 'Enter your order number for the Theme Updater and click "Check License".<br>After your license information is verified, you will be redirected, and you can start the 1-click updater.<br>The theme data will automatically be downloaded from the Premium Contao Themes server to your server and then installed.';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['enter_theme_license_info'] = 'Enter your order number for the theme.';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['button_license_buy'] = 'Purchase Theme Updater License';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['manual_table']['head']['task'] = 'Task';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['manual_table']['head']['description'] = 'Description';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['manual_table']['head']['status'] = 'Completed';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['manual_table']['head']['iframe'] = 'Documentation';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['submit_commit'] = 'Save progress';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['submit_done'] = 'Complete update';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['empty_tasks'] = 'No further tasks.';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['TEMPLATE']['up_to_date'] = 'No new version available';
/**
 * Breadcrumb
 */
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BREADCRUMB']['welcome'][0] = 'Start';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BREADCRUMB']['welcome'][1] = 'This is where it all begins';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BREADCRUMB']['validation'][0] = 'License Check';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BREADCRUMB']['validation'][1] = 'Your license is being verified.';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BREADCRUMB']['accepted'][0] = 'License Valid';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BREADCRUMB']['accepted'][1] = 'Your license has been validated.';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BREADCRUMB']['not_accepted'][0] = 'License Not Valid';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BREADCRUMB']['not_accepted'][1] = 'Your license could not be validated.';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BREADCRUMB']['loading'][0] = 'Loading Data';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BREADCRUMB']['loading'][1] = 'The data is being loaded';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BREADCRUMB']['installation.unzip'][0] = 'Unpacking Data';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BREADCRUMB']['installation.unzip'][1] = 'The data is being unpacked';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BREADCRUMB']['installation.copy_files'][0] = 'Copying Data';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BREADCRUMB']['installation.copy_files'][1] = 'The data is being distributed to the target directories.';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BREADCRUMB']['installation.clear_cache'][0] = 'Clearing Prod. Cache';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BREADCRUMB']['installation.clear_cache'][1] = 'Clearing Prod. Cache.';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BREADCRUMB']['installation.db_update_modules'][0] = 'Database Update';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BREADCRUMB']['installation.db_update_modules'][1] = 'The database is being updated with module information.';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BREADCRUMB']['installation.sql_template_import'][0] = 'Executing Installation Template Import...';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BREADCRUMB']['installation.sql_template_import'][1] = 'Installing the SQL installation template for the demo data.';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BREADCRUMB']['installation.sql_template_wait'][0] = 'Importing Installation Template...';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BREADCRUMB']['installation.sql_template_wait'][1] = 'Importing installation template...';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BREADCRUMB']['manual_adjustment'][0] = 'Manual Adjustments';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BREADCRUMB']['manual_adjustment'][1] = 'Guide for manual adjustments.';
/**
 * Status
 */
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['STATUS']['welcome'] = '';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['STATUS']['validation'] = 'License Check';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['STATUS']['accepted'] = 'License Valid';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['STATUS']['not_accepted'] = 'License Not Valid';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['STATUS']['not_supported'] = 'This product is not supported.';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['STATUS']['choose_product'] = 'Choose Product...';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['STATUS']['loading'] = 'Loading Data';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['STATUS']['session_lost'] = 'License Session Expired';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['STATUS']['installation.unzip'] = 'Unpacking Data';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['STATUS']['installation.copy_files'] = 'Copying Data';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['STATUS']['installation.clear_cache'] = 'Clearing Prod. Cache';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['STATUS']['installation.db_update_modules'] = 'Database Update';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['STATUS']['manual_adjustment'] = 'Manual Adjustments';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['STATUS']['done'] = 'Completed';
/**
 * Ajax infotexts
 */
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['AJAX_INFO']['validation'] = 'Checking license...';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['AJAX_INFO']['loading'] = 'Loading file "%s"...';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['AJAX_INFO']['sql_template_import'] = 'Importing installation template...';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['AJAX_INFO']['clear_cache'] = 'Clearing cache...';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['AJAX_INFO']['copy_files'] = 'Copying files...';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['AJAX_INFO']['unzip'] = 'Unpacking files...';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['AJAX_INFO']['db_update_modules'] = 'Updating database...';
/**
 * Backend descriptions
 */
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BACKEND_DESCRIPTION']['welcome'] = 'Welcome to the Theme Updater (' . \PCT_THEME_UPDATER . ')';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BACKEND_DESCRIPTION']['theme_updater_desc'] = 'With the Theme Updater, the theme and all its modules can be updated. All customizations made via the ThemeDesigner, as well as those in customize.css/js and the templates/ folder, remain intact. For a Contao update, we recommend our <a href="https://www.premium-contao-themes.com/contao-installer.html" target="_blank">Contao Installer.</a>';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BACKEND_DESCRIPTION']['ready'] = 'Update: <span class="italic">%s</span>';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BACKEND_DESCRIPTION']['loading'] = 'Loading data...';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BACKEND_DESCRIPTION']['choose_product'] = 'Your license includes more than one product.<br>Please select the product to install.';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BACKEND_DESCRIPTION']['error'] = 'Errors occurred.';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BACKEND_DESCRIPTION']['file_not_exists'] = 'File no longer exists';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BACKEND_DESCRIPTION']['access_denied'] = 'License validation failed.';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BACKEND_DESCRIPTION']['not_supported'] = 'The selected product is not supported.';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BACKEND_DESCRIPTION']['session_lost'] = 'The license session has expired. Please restart the installation.';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BACKEND_DESCRIPTION']['installation.unzip'] = 'Unpacking the data zip...';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BACKEND_DESCRIPTION']['installation.copy_files'] = 'Copying the files to their destination...';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BACKEND_DESCRIPTION']['installation.clear_cache'] = 'Cache is being rebuilt with the new information.';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BACKEND_DESCRIPTION']['installation.db_update_modules'] = 'The database is being updated with the new module information.';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BACKEND_DESCRIPTION']['installation.sql_template_wait'] = 'The demo website (installation template) is ready to be installed.';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BACKEND_DESCRIPTION']['installation.sql_template_import'] = 'Importing the installation template.';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BACKEND_DESCRIPTION']['version_conflict'] = 'Version conflict';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BACKEND_DESCRIPTION']['manual_adjustment'] = 'Manual Adjustments';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BACKEND_DESCRIPTION']['done'] = 'Summary';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BACKEND_DESCRIPTION']['agreement'] = 'I have created a current backup of all relevant data, which I can use to restore the website if needed. All theme files (except templates/, customize.css/js, and ThemeDesigner customizations) will be overwritten. An update in a live environment is not recommended. Seamedia® Themes assumes no liability or warranty for updates. (*Required field)';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['BACKEND_DESCRIPTION']['delete_demo_files'] = 'Delete demo files: At the end of the update, clear the folders: /templates/demo_installer, files/cto_layout/img/delete_this<p>Note: The data is needed for the demo installer to function.</p>';
/**
 * Categories
 */
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['CATEGORIES']['fe_modules'] = 'Frontend Modules';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['CATEGORIES']['layout'] = 'Page Layouts';
$GLOBALS['TL_LANG']['PCT_THEME_UPDATER']['CATEGORIES']['various'] = 'Other Changes';
