<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2014
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['combiner'][0] 		= 'Bedingung zum nächsten Filter';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['combiner'][1] 		= 'Wählen Sie wie die nächste Abfrage (Filter) kombiniert werden soll.';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['combiner']['and'] 	= 'AND';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['combiner']['or'] 	= 'OR';

$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['combiner_label']	= 'Abfrage %s';