<?php
/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2013 
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options']['list'][0] = 'Listentyp';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options']['list'][1] = 'Wählen Sie den Listentyp aus.';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options']['list']['ordered'] = 'Nummerierte Liste';
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options']['list']['unordered'] = 'Unnummeriete Liste';