<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2014
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['min_value'][0] 			= 'Minimum, Untere Grenze';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['min_value'][1] 			= 'Geben Sie die untere Grenze des Filters ein.';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['max_value'][0] 			= 'Maximum, Obere Grenze';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['max_value'][1] 			= 'Geben Sie die obere Grenze des Filters ein.';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['range_mode'][0] 		= 'Operation';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['range_mode'][1] 		= 'Choose the filter option. "Between" inlcudes the jquery UI library to the page.';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['range_mode']['ht'] 		= 'Higher [>]';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['range_mode']['hte'] 	= 'Higher-euqal [>=]';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['range_mode']['lt'] 		= 'Lower [<]';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['range_mode']['lte'] 	= 'Lower-equal [<=]';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['range_mode']['between'] = 'Between';
$GLOBALS['TL_LANG']['tl_pct_customelement_filter']['range_mode']['equal'] 	= 'Equals [==]';