<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2016
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
/**
 * Defaults
 */
$GLOBALS['TL_LANG']['pct_themer']['headline'] 					= 'PCT theme export: %s';
$GLOBALS['TL_LANG']['pct_themer']['infos']['collecting_data'] 	= 'Collecting data...';
$GLOBALS['TL_LANG']['pct_themer']['infos']['file_created'] 		= 'The demo-template file (%s) has been saved to /templates.';
$GLOBALS['TL_LANG']['pct_themer']['submit_complete'] 			= 'Complete';
$GLOBALS['TL_LANG']['pct_themer']['submit_download'] 			= 'Download';
$GLOBALS['TL_LANG']['pct_themer']['alert_no_theme_selected'] 	= 'Export failed: The root page has no theme selected!';
$GLOBALS['TL_LANG']['pct_themer']['import_success'] 			= 'Theme Demo import completed';
$GLOBALS['TL_LANG']['pct_themedesigner']['backend_info']		= '<span style="line-height:24px;">ThemeDesigner is <strong>active</strong>. Deactivate the ThemeDesigner, to switch to Live node.</span>';
$GLOBALS['TL_LANG']['pct_themedesigner']['backend_info_green']	= '<span style="line-height:24px;">ThemeDesigner is running in <strong>Live mode</strong>.';
$GLOBALS['TL_LANG']['pct_themedesigner']['nosave_info']			= 'No saved version yet';

/**
 * Demoinstaller
 */
$GLOBALS['TL_LANG']['pct_demoinstaller']['contao_theme']				= 'You have more than one Contao theme record installed. Please choose the target theme:';
$GLOBALS['TL_LANG']['pct_demoinstaller']['counter']						= 'Demos: %s';
$GLOBALS['TL_LANG']['pct_demoinstaller']['submit_install']				= 'Install';
$GLOBALS['TL_LANG']['pct_demoinstaller']['submit_show']					= 'Show me';
$GLOBALS['TL_LANG']['pct_demoinstaller']['submit_customize']			= 'Customize';
$GLOBALS['TL_LANG']['pct_demoinstaller']['submit_preview']				= 'Preview';
$GLOBALS['TL_LANG']['pct_demoinstaller']['categories'][0] 				= 'Categories';
$GLOBALS['TL_LANG']['pct_demoinstaller']['categories'][1] 				= 'Select categories';
$GLOBALS['TL_LANG']['pct_demoinstaller']['categories']['business'] 		= 'Business';
$GLOBALS['TL_LANG']['pct_demoinstaller']['categories']['creative'] 		= 'Creative';
$GLOBALS['TL_LANG']['pct_demoinstaller']['categories']['portfolio'] 	= 'Portfolio';
$GLOBALS['TL_LANG']['pct_demoinstaller']['categories']['blog'] 			= 'Blog';
$GLOBALS['TL_LANG']['pct_demoinstaller']['categories']['onepage'] 		= 'OnePage';
$GLOBALS['TL_LANG']['pct_demoinstaller']['categories']['other'] 		= 'Misc';
$GLOBALS['TL_LANG']['pct_demoinstaller']['categories']['presets'] 		= 'Presets';
$GLOBALS['TL_LANG']['pct_demoinstaller']['categories']['new'] 			= 'New X6';