<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2016
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_page']['pct_theme'][0]			= 'Layout selection';
$GLOBALS['TL_LANG']['tl_page']['pct_theme'][1]			= 'Please choose a layout.';
$GLOBALS['TL_LANG']['tl_page']['pct_theme_import'][0]	= 'Import demo data in this root page';
$GLOBALS['TL_LANG']['tl_page']['pct_theme_import'][1]	= 'Demo data will be imported on record save';
$GLOBALS['TL_LANG']['tl_page']['pct_theme_cto'][0]		= 'Choose theme';
$GLOBALS['TL_LANG']['tl_page']['pct_theme_cto'][1]		= 'Please choose the theme record as target for module.';
$GLOBALS['TL_LANG']['tl_page']['pct_themedesigner_hidden'][0] = 'Hide Theme-Designer';
$GLOBALS['TL_LANG']['tl_page']['pct_themedesigner_hidden'][1] = 'Hide the Theme-Designer for this page tree. The Theme-Designer customizations remain active.';


/**
 * Legends
 */
$GLOBALS['TL_LANG']['tl_page']['pct_theme_legend']		= 'Theme-Designer settings';

// References
if(count($GLOBALS['PCT_THEMER']['THEMES']) > 0)
{
	foreach($GLOBALS['PCT_THEMER']['THEMES'] as $key => $arr)
	{
		$GLOBALS['TL_LANG']['tl_page']['pct_theme'][$key] = $arr['label'] ?? $key;
	}
}

/**
 * Operations
 */
$GLOBALS['TL_LANG']['tl_page']['pct_theme_export'][0]	= 'Export theme demo records of page %s';
$GLOBALS['TL_LANG']['tl_page']['pct_theme_export'][1]	= 'Export theme demo records of page %s';
